// app/client/src/app/components/nav-sidebar/nav-sidebar.component.ts
import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Output, inject } from '@angular/core';

import { AppStateService, PageId } from '../../core/state/app-state.service';

@Component({
  selector: 'app-nav-sidebar',
  imports: [CommonModule],
  templateUrl: './nav-sidebar.component.html',
  styleUrl: './nav-sidebar.component.scss',
})
export class NavSidebarComponent {
  @Output() navigate = new EventEmitter<PageId>();
  @Output() helpRequested = new EventEmitter<void>();

  readonly stateService = inject(AppStateService);

  readonly navItems: Array<{ pageId: PageId; label: string }> = [
    { pageId: 'dili-agent', label: 'DILI Agent' },
    { pageId: 'clinical-sessions', label: 'Clinical Sessions' },
    { pageId: 'data-inspection', label: 'Data Inspection' },
    { pageId: 'model-config', label: 'Configurations' },
  ];

  onNavigate(pageId: PageId): void {
    this.navigate.emit(pageId);
  }

  openHelp(): void {
    this.helpRequested.emit();
  }

  onNavTabKeydown(event: KeyboardEvent, pageId: PageId): void {
    const index = this.navItems.findIndex((item) => item.pageId === pageId);
    if (index < 0) {
      return;
    }

    let nextIndex: number | null = null;
    switch (event.key) {
      case 'ArrowRight':
      case 'ArrowDown':
        nextIndex = (index + 1) % this.navItems.length;
        break;
      case 'ArrowLeft':
      case 'ArrowUp':
        nextIndex = (index - 1 + this.navItems.length) % this.navItems.length;
        break;
      case 'Home':
        nextIndex = 0;
        break;
      case 'End':
        nextIndex = this.navItems.length - 1;
        break;
      default:
        break;
    }

    if (nextIndex === null) {
      return;
    }
    event.preventDefault();
    this.onNavigate(this.navItems[nextIndex].pageId);
  }

  toggleTheme(): void {
    this.stateService.toggleTheme();
  }

  get isDarkTheme(): boolean {
    return this.stateService.state().theme === 'dark';
  }

  get themeAriaLabel(): string {
    return this.isDarkTheme ? 'Switch to light theme' : 'Switch to dark theme';
  }
}

<div class="app-top-nav">
  <header class="app-header">
    <div class="app-header-content">
      <div class="app-header-brand">
        <span class="app-header-logo">
          <img src="/diligent-logo.png" alt="Diligent logo" />
        </span>
        <span class="app-header-wordmark">DILIGENT Clinical Copilot</span>
      </div>
      <nav class="tab-bar" aria-label="Main navigation">
        <div class="tab-items" role="tablist" aria-label="Main navigation tabs">
          @for (item of navItems; track item.pageId) {
            <button
              type="button"
              class="tab-item"
              [class.active]="stateService.state().activePage === item.pageId"
              role="tab"
              [attr.aria-selected]="stateService.state().activePage === item.pageId"
              [attr.tabindex]="stateService.state().activePage === item.pageId ? '0' : '-1'"
              (click)="onNavigate(item.pageId)"
              (keydown)="onNavTabKeydown($event, item.pageId)"
              [attr.aria-current]="stateService.state().activePage === item.pageId ? 'page' : null"
              [title]="item.label"
            >
              <span class="tab-label">{{ item.label }}</span>
            </button>
          }
        </div>
      </nav>
      <div class="app-header-actions">
        <button
          type="button"
          class="app-header-icon-btn app-header-help-btn"
          (click)="openHelp()"
          aria-label="Open Help and Tips"
          title="Open Help and Tips"
        >
          Help
        </button>
        <button
          type="button"
          class="app-header-icon-btn"
          (click)="toggleTheme()"
          [attr.aria-label]="themeAriaLabel"
          [attr.title]="themeAriaLabel"
        >
          @if (isDarkTheme) {
            <svg class="theme-icon" viewBox="0 0 24 24" aria-hidden="true">
              <defs>
                <linearGradient id="themeSunCore" x1="4" y1="4" x2="20" y2="20" gradientUnits="userSpaceOnUse">
                  <stop offset="0" stop-color="#fde68a" />
                  <stop offset="1" stop-color="#fbbf24" />
                </linearGradient>
              </defs>
              <circle cx="12" cy="12" r="4.45" fill="url(#themeSunCore)" />
              <path fill="#f59e0b" d="M12 1.6a.85.85 0 0 1 .85.85V5.1a.85.85 0 0 1-1.7 0V2.45A.85.85 0 0 1 12 1.6Zm0 17.3a.85.85 0 0 1 .85.85v1.8a.85.85 0 1 1-1.7 0v-1.8a.85.85 0 0 1 .85-.85ZM4.09 4.08a.85.85 0 0 1 1.2 0L7.16 5.96a.85.85 0 0 1-1.2 1.2L4.1 5.29a.85.85 0 0 1 0-1.21Zm12.75 12.76a.85.85 0 0 1 1.2 0l1.87 1.88a.85.85 0 1 1-1.2 1.2l-1.87-1.88a.85.85 0 0 1 0-1.2Z" />
              <path fill="#5bc8ac" d="M1.6 12a.85.85 0 0 1 .85-.85h2.66a.85.85 0 1 1 0 1.7H2.45A.85.85 0 0 1 1.6 12Zm17.3 0a.85.85 0 0 1 .85-.85h1.8a.85.85 0 1 1 0 1.7h-1.8a.85.85 0 0 1-.85-.85ZM4.09 19.92a.85.85 0 0 1 0-1.2l1.87-1.88a.85.85 0 1 1 1.2 1.2l-1.87 1.88a.85.85 0 0 1-1.2 0Zm12.75-12.76a.85.85 0 0 1 0-1.2l1.87-1.88a.85.85 0 1 1 1.2 1.2l-1.87 1.88a.85.85 0 0 1-1.2 0Z" />
            </svg>
          } @else {
            <img class="theme-icon theme-icon-image" src="/dark-mode-icon.png" alt="" aria-hidden="true" />
          }
        </button>
      </div>
    </div>
  </header>
</div>

// DILIGENT/client/src/components/NavSidebar.tsx
import React from "react";
import { PageId, useAppState } from "../context/AppStateContext";

// ---------------------------------------------------------------------------
// Icon Components
// ---------------------------------------------------------------------------
const DiligentLogo = () => (
    <svg
        viewBox="0 0 120 36"
        role="img"
        aria-labelledby="diligent-logo-title"
    >
        <title id="diligent-logo-title">Application logo</title>
        <defs>
            <linearGradient id="diligent-mark-gradient" x1="0%" y1="0%" x2="100%" y2="100%">
                <stop offset="0%" stopColor="#1f9d76" />
                <stop offset="100%" stopColor="#14945f" />
            </linearGradient>
        </defs>
        <rect x="2" y="2" width="32" height="32" rx="9" fill="url(#diligent-mark-gradient)" />
        <rect x="2" y="2" width="32" height="32" rx="9" fill="none" stroke="rgba(15, 23, 42, 0.08)" />
        <path
            d="M10 26V10h6.5c6 0 9.5 3.1 9.5 8s-3.5 8-9.5 8H10zm5-4h1.2c3.2 0 5-1.3 5-4s-1.8-4-5-4H15v8z"
            fill="#effcf6"
        />
        <text x="42" y="16" fill="currentColor" fontSize="10.2" fontWeight="800" letterSpacing="0.13em">
            DILIGENT
        </text>
        <text x="42" y="27" fill="currentColor" fillOpacity="0.74" fontSize="7.4" fontWeight="600" letterSpacing="0.09em">
            CLINICAL COPILOT
        </text>
    </svg>
);

const AgentIcon = () => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
        <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" />
        <line x1="9" y1="10" x2="15" y2="10" />
    </svg>
);

const DataIcon = () => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
        <ellipse cx="12" cy="6" rx="7" ry="3" />
        <path d="M5 6v6c0 1.66 3.13 3 7 3s7-1.34 7-3V6" />
        <path d="M5 12v6c0 1.66 3.13 3 7 3s7-1.34 7-3v-6" />
    </svg>
);

const SettingsIcon = () => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
        <circle cx="12" cy="12" r="3" />
        <path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z" />
    </svg>
);

// ---------------------------------------------------------------------------
// NavItem
// ---------------------------------------------------------------------------
interface NavItemProps {
    pageId: PageId;
    icon: React.ReactNode;
    label: string;
    isActive: boolean;
    onClick: (pageId: PageId) => void;
}

function NavItem({ pageId, icon, label, isActive, onClick }: NavItemProps): React.JSX.Element {
    return (
        <button
            type="button"
            className={`tab-item ${isActive ? "active" : ""}`}
            onClick={() => onClick(pageId)}
            aria-current={isActive ? "page" : undefined}
            title={label}
        >
            <span className="tab-icon">{icon}</span>
            <span className="tab-label">{label}</span>
        </button>
    );
}

// ---------------------------------------------------------------------------
// NavTabs
// ---------------------------------------------------------------------------
interface NavTabsProps {
    onNavigate: (pageId: PageId) => void;
}

export function NavTabs({ onNavigate }: NavTabsProps): React.JSX.Element {
    const { state, toggleTheme } = useAppState();

    const navItems: { pageId: PageId; icon: React.ReactNode; label: string }[] = [
        { pageId: "dili-agent", icon: <AgentIcon />, label: "DILI Agent" },
        { pageId: "data-inspection", icon: <DataIcon />, label: "Data Inspection" },
        { pageId: "model-config", icon: <SettingsIcon />, label: "Model Configurations" },
    ];

    return (
        <div className="app-top-nav">
            <header className="app-header">
                <div className="app-header-content">
                    <div className="app-header-brand">
                        <span className="app-header-logo">
                            <DiligentLogo />
                        </span>
                    </div>
                    <nav className="tab-bar" aria-label="Main navigation">
                        <div className="tab-items">
                            {navItems.map((item) => (
                                <NavItem
                                    key={item.pageId}
                                    pageId={item.pageId}
                                    icon={item.icon}
                                    label={item.label}
                                    isActive={state.activePage === item.pageId}
                                    onClick={onNavigate}
                                />
                            ))}
                        </div>
                    </nav>
                    <div className="app-header-actions">
                        <button type="button" className="app-header-icon-btn" aria-label="Help">
                            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                                <circle cx="12" cy="12" r="10" />
                                <path d="M9.09 9a3 3 0 0 1 5.82 1c0 2-3 3-3 3" />
                                <line x1="12" y1="17" x2="12.01" y2="17" />
                            </svg>
                        </button>
                        <button
                            type="button"
                            className="app-header-icon-btn"
                            onClick={toggleTheme}
                            aria-label="Toggle dark mode"
                            title="Toggle dark mode"
                        >
                            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                                <path d="M21 12.79A9 9 0 1 1 11.21 3c0 .28-.01.56-.01.84a8 8 0 0 0 9.8 7.95z" />
                            </svg>
                        </button>
                        <span className="app-header-avatar" aria-hidden="true">DR</span>
                    </div>
                </div>
            </header>
        </div>
    );
}
