// DILIGENT/client/src/app/components/status-message/status-message.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';

export type StatusTone = 'is-error' | 'is-info' | 'is-success';

export function resolveStatusTone(message: string): StatusTone {
  const normalized = message.trim().toUpperCase();
  if (!normalized) {
    return 'is-info';
  }
  if (normalized.startsWith('[ERROR]')) {
    return 'is-error';
  }
  if (normalized.startsWith('[INFO]')) {
    return 'is-info';
  }
  return 'is-success';
}

@Component({
  selector: 'app-status-message',
  standalone: true,
  imports: [CommonModule],
  template: `
    @if (normalizedMessage) {
      <p
        [class]="className + ' ' + resolvedTone"
        [attr.role]="resolvedTone === 'is-error' ? 'alert' : 'status'"
        [attr.aria-live]="resolvedTone === 'is-error' ? 'assertive' : 'polite'"
      >
        {{ normalizedMessage }}
      </p>
    }
  `,
})
export class StatusMessageComponent {
  @Input() message = '';
  @Input() tone?: StatusTone;
  @Input() className = 'model-config-status-message';

  get normalizedMessage(): string {
    return this.message.trim();
  }

  get resolvedTone(): StatusTone {
    return this.tone ?? resolveStatusTone(this.normalizedMessage);
  }
}

// DILIGENT/client/src/components/StatusMessage.tsx
import React from "react";

export type StatusTone = "is-error" | "is-info" | "is-success";

interface StatusMessageProps {
  readonly message: string;
  readonly tone?: StatusTone;
  readonly className?: string;
}

export function resolveStatusTone(message: string): StatusTone {
  const normalized = message.trim().toUpperCase();
  if (!normalized) {
    return "is-info";
  }
  if (normalized.startsWith("[ERROR]")) {
    return "is-error";
  }
  if (normalized.startsWith("[INFO]")) {
    return "is-info";
  }
  return "is-success";
}

export function StatusMessage({
  message,
  tone,
  className = "model-config-status-message",
}: StatusMessageProps): React.JSX.Element | null {
  const normalized = message.trim();
  if (!normalized) {
    return null;
  }

  const resolvedTone = tone ?? resolveStatusTone(normalized);
  return (
    <p
      className={`${className} ${resolvedTone}`}
      role={resolvedTone === "is-error" ? "alert" : "status"}
      aria-live={resolvedTone === "is-error" ? "assertive" : "polite"}
    >
      {normalized}
    </p>
  );
}
