// DILIGENT/client/src/components/AccessKeyModal.tsx
import React, { useEffect, useMemo, useState } from "react";

import {
    activateAccessKey,
    createAccessKey,
    deleteAccessKey,
    fetchAccessKeys,
} from "../services/api";
import { AccessKeyProvider, AccessKeyRecord } from "../types";

const MASKED_KEY_LABEL = "********************";

const CloseIcon = () => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <line x1="18" y1="6" x2="6" y2="18" />
        <line x1="6" y1="6" x2="18" y2="18" />
    </svg>
);

const LockIcon = () => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <rect x="4" y="11" width="16" height="9" rx="2" />
        <path d="M8 11V8a4 4 0 1 1 8 0v3" />
    </svg>
);

const EyeIcon = () => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M2 12s3.6-6 10-6 10 6 10 6-3.6 6-10 6-10-6-10-6Z" />
        <circle cx="12" cy="12" r="3" />
    </svg>
);

const TrashIcon = () => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M3 6h18" />
        <path d="M8 6V4h8v2" />
        <path d="M6 6l1 14h10l1-14" />
    </svg>
);

interface AccessKeyModalProps {
    readonly isOpen: boolean;
    readonly provider: AccessKeyProvider;
    readonly providerLabel: string;
    readonly onClose: () => void;
}

function obfuscateFingerprint(value: string): string {
    const fingerprint = (value || "").trim();
    if (fingerprint.length <= 10) {
        return `fp: ${fingerprint || "unknown"}`;
    }
    return `fp: ${fingerprint.slice(0, 6)}...${fingerprint.slice(-4)}`;
}

function formatTimestamp(value: string | null): string {
    if (!value) {
        return "Not used";
    }
    const parsed = new Date(value);
    if (Number.isNaN(parsed.getTime())) {
        return "Not used";
    }
    return parsed.toLocaleString();
}

export function AccessKeyModal({
    isOpen,
    provider,
    providerLabel,
    onClose,
}: AccessKeyModalProps): React.JSX.Element | null {
    const [keys, setKeys] = useState<AccessKeyRecord[]>([]);
    const [isLoading, setIsLoading] = useState(false);
    const [isSaving, setIsSaving] = useState(false);
    const [newKeyValue, setNewKeyValue] = useState("");
    const [errorMessage, setErrorMessage] = useState("");
    const [visibleRows, setVisibleRows] = useState<Record<number, boolean>>({});

    const hasKeys = keys.length > 0;
    const sortedKeys = useMemo(
        () => [...keys].sort((left, right) => Number(right.is_active) - Number(left.is_active) || right.id - left.id),
        [keys],
    );

    const loadKeys = async () => {
        setIsLoading(true);
        setErrorMessage("");
        try {
            const payload = await fetchAccessKeys(provider);
            setKeys(payload);
        } catch (error) {
            const message = error instanceof Error ? error.message : "Unable to load access keys.";
            setErrorMessage(message);
        } finally {
            setIsLoading(false);
        }
    };

    useEffect(() => {
        if (!isOpen) {
            return;
        }
        void loadKeys();
    }, [isOpen, provider]);

    const handleAdd = async () => {
        const candidate = newKeyValue.trim();
        if (!candidate) {
            setErrorMessage("Please paste a key before adding.");
            return;
        }
        setIsSaving(true);
        setErrorMessage("");
        try {
            await createAccessKey(provider, candidate);
            setNewKeyValue("");
            await loadKeys();
        } catch (error) {
            const message = error instanceof Error ? error.message : "Unable to add access key.";
            setErrorMessage(message);
        } finally {
            setIsSaving(false);
        }
    };

    const handleActivate = async (keyId: number) => {
        setIsSaving(true);
        setErrorMessage("");
        try {
            const activated = await activateAccessKey(keyId);
            setKeys((current) => current.map((item) => ({
                ...item,
                is_active: item.id === activated.id,
                updated_at: item.id === activated.id ? activated.updated_at : item.updated_at,
                last_used_at: item.id === activated.id ? activated.last_used_at : item.last_used_at,
            })));
        } catch (error) {
            const message = error instanceof Error ? error.message : "Unable to activate access key.";
            setErrorMessage(message);
        } finally {
            setIsSaving(false);
        }
    };

    const handleDelete = async (keyId: number) => {
        setIsSaving(true);
        setErrorMessage("");
        try {
            await deleteAccessKey(keyId);
            setKeys((current) => current.filter((item) => item.id !== keyId));
            setVisibleRows((current) => {
                const next = { ...current };
                delete next[keyId];
                return next;
            });
        } catch (error) {
            const message = error instanceof Error ? error.message : "Unable to delete access key.";
            setErrorMessage(message);
        } finally {
            setIsSaving(false);
        }
    };

    const toggleVisibility = (keyId: number) => {
        setVisibleRows((current) => ({ ...current, [keyId]: !current[keyId] }));
    };

    if (!isOpen) {
        return null;
    }

    return (
        <div className="modal-overlay">
            <dialog className="modal-container access-key-modal" aria-modal="true" aria-labelledby="access-key-modal-title" open>
                <div className="modal-header">
                    <div className="modal-header-content">
                        <p className="modal-title" id="access-key-modal-title">{providerLabel} Access Keys</p>
                        <p className="modal-subtitle">Stored encrypted at rest. Activate one key at a time for this provider.</p>
                    </div>
                    <button
                        className="modal-close"
                        type="button"
                        onClick={onClose}
                        aria-label="Close access key modal"
                    >
                        <CloseIcon />
                    </button>
                </div>

                <div className="modal-body">
                    <section className="modal-section">
                        <p className="modal-section-title">Add New Key</p>
                        <div className="access-key-input-row">
                            <input
                                className="access-key-input"
                                type="password"
                                placeholder="Paste access key"
                                value={newKeyValue}
                                onChange={(event) => setNewKeyValue(event.target.value)}
                                disabled={isSaving}
                            />
                            <button className="btn btn-primary access-key-add-btn" type="button" onClick={() => { void handleAdd(); }} disabled={isSaving}>
                                Add
                            </button>
                        </div>
                    </section>

                    <section className="modal-section">
                        <p className="modal-section-title">Stored Keys</p>
                        {isLoading && <p className="access-key-empty">Loading keys...</p>}
                        {!isLoading && !hasKeys && <p className="access-key-empty">No keys stored for this provider.</p>}
                        {!isLoading && hasKeys && (
                            <ul className="access-key-list">
                                {sortedKeys.map((item) => (
                                    <li key={item.id} className={`access-key-row ${item.is_active ? "is-active" : ""}`}>
                                        <div className="access-key-meta">
                                            <p className="access-key-fingerprint">
                                                {visibleRows[item.id] ? obfuscateFingerprint(item.fingerprint) : MASKED_KEY_LABEL}
                                            </p>
                                            <p className="access-key-timestamp">Last used: {formatTimestamp(item.last_used_at)}</p>
                                        </div>
                                        <div className="access-key-actions">
                                            <button
                                                className={`access-key-action ${item.is_active ? "is-active" : ""}`}
                                                type="button"
                                                onClick={() => { void handleActivate(item.id); }}
                                                disabled={isSaving}
                                                title={item.is_active ? "Active key" : "Activate key"}
                                                aria-label={item.is_active ? "Active key" : "Activate key"}
                                            >
                                                <LockIcon />
                                            </button>
                                            <button
                                                className="access-key-action"
                                                type="button"
                                                onClick={() => toggleVisibility(item.id)}
                                                disabled={isSaving}
                                                title="Toggle fingerprint view"
                                                aria-label="Toggle fingerprint view"
                                            >
                                                <EyeIcon />
                                            </button>
                                            <button
                                                className="access-key-action is-danger"
                                                type="button"
                                                onClick={() => { void handleDelete(item.id); }}
                                                disabled={isSaving}
                                                title="Delete key"
                                                aria-label="Delete key"
                                            >
                                                <TrashIcon />
                                            </button>
                                        </div>
                                    </li>
                                ))}
                            </ul>
                        )}
                    </section>

                    {!!errorMessage && <p className="model-config-status-message">[ERROR] {errorMessage}</p>}
                </div>
            </dialog>
        </div>
    );
}

// app/client/src/app/pages/model-config/components/access-key-modal.component.ts
import { CommonModule } from '@angular/common';
import {
  Component,
  EventEmitter,
  Input,
  OnChanges,
  Output,
  SimpleChanges,
  computed,
  signal,
} from '@angular/core';
import { FormsModule } from '@angular/forms';

import { AccessKeyProvider, AccessKeyRecord } from '../../../core/models/types';
import {
  activateAccessKey,
  createAccessKey,
  deleteAccessKey,
  fetchAccessKeys,
} from '../../../core/services/model-config-api';
import { ModalShellComponent } from '../../../components/modal-shell/modal-shell.component';
import { StatusMessageComponent } from '../../../components/status-message/status-message.component';

const MASKED_KEY_LABEL = '********************';
const MIN_ACCESS_KEY_LENGTH = 16;

function obfuscateFingerprint(value: string): string {
  const fingerprint = (value || '').trim();
  if (fingerprint.length <= 10) {
    return `fp: ${fingerprint || 'unknown'}`;
  }
  return `fp: ${fingerprint.slice(0, 6)}...${fingerprint.slice(-4)}`;
}

function formatTimestamp(value: string | null): string {
  if (!value) {
    return 'Not used';
  }
  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) {
    return 'Not used';
  }
  return parsed.toLocaleString();
}

@Component({
  selector: 'app-access-key-modal',
  standalone: true,
  imports: [CommonModule, FormsModule, ModalShellComponent, StatusMessageComponent],
  templateUrl: './access-key-modal.component.html',
  styleUrl: './access-key-modal.component.scss',
})
export class AccessKeyModalComponent implements OnChanges {
  @Input() isOpen = false;
  @Input() provider: AccessKeyProvider = 'openai';
  @Input() providerLabel = 'OpenAI';
  @Output() closed = new EventEmitter<void>();
  @Output() keysChanged = new EventEmitter<void>();

  readonly keys = signal<AccessKeyRecord[]>([]);
  readonly isLoading = signal(false);
  readonly isSaving = signal(false);
  readonly newKeyValue = signal('');
  readonly errorMessage = signal('');
  readonly visibleRows = signal<Record<number, boolean>>({});
  private loadSequence = 0;

  ngOnChanges(changes: SimpleChanges): void {
    if ((changes['isOpen'] || changes['provider']) && this.isOpen) {
      void this.loadKeys();
    }
  }

  readonly sortedKeys = computed(() => [...this.keys()].sort(
      (left, right) => Number(right.is_active) - Number(left.is_active) || right.id - left.id,
    ));

  readonly hasKeys = computed(() => this.keys().length > 0);

  async loadKeys(): Promise<void> {
    const loadId = ++this.loadSequence;
    this.isLoading.set(true);
    this.errorMessage.set('');
    try {
      const keys = await fetchAccessKeys(this.provider);
      if (loadId === this.loadSequence) {
        this.keys.set(keys);
      }
    } catch (error) {
      if (loadId === this.loadSequence) {
        this.errorMessage.set(error instanceof Error ? error.message : 'Unable to load access keys.');
      }
    } finally {
      if (loadId === this.loadSequence) {
        this.isLoading.set(false);
      }
    }
  }

  async addKey(): Promise<void> {
    const candidate = this.newKeyValue().trim();
    if (!candidate) {
      this.errorMessage.set('Please paste a key before adding.');
      return;
    }
    if (candidate.length < MIN_ACCESS_KEY_LENGTH) {
      this.errorMessage.set(`Access keys must be at least ${MIN_ACCESS_KEY_LENGTH} characters.`);
      return;
    }
    this.isSaving.set(true);
    this.errorMessage.set('');
    try {
      await createAccessKey(this.provider, candidate);
      this.newKeyValue.set('');
      await this.loadKeys();
      this.keysChanged.emit();
    } catch (error) {
      this.errorMessage.set(error instanceof Error ? error.message : 'Unable to add access key.');
    } finally {
      this.isSaving.set(false);
    }
  }

  async activateKey(keyId: number): Promise<void> {
    this.isSaving.set(true);
    this.errorMessage.set('');
    try {
      const activated = await activateAccessKey(keyId, this.provider);
      this.keys.update((items) => items.map((item) => ({
        ...item,
        is_active: item.id === activated.id,
        updated_at: item.id === activated.id ? activated.updated_at : item.updated_at,
        last_used_at: item.id === activated.id ? activated.last_used_at : item.last_used_at,
      })));
      this.keysChanged.emit();
    } catch (error) {
      this.errorMessage.set(error instanceof Error ? error.message : 'Unable to activate access key.');
    } finally {
      this.isSaving.set(false);
    }
  }

  async deleteKey(keyId: number): Promise<void> {
    this.isSaving.set(true);
    this.errorMessage.set('');
    try {
      await deleteAccessKey(keyId, this.provider);
      this.keys.update((items) => items.filter((item) => item.id !== keyId));
      this.visibleRows.update((rows) => {
        const next = { ...rows };
        delete next[keyId];
        return next;
      });
      this.keysChanged.emit();
    } catch (error) {
      this.errorMessage.set(error instanceof Error ? error.message : 'Unable to delete access key.');
    } finally {
      this.isSaving.set(false);
    }
  }

  toggleVisibility(keyId: number): void {
    this.visibleRows.update((rows) => ({ ...rows, [keyId]: !rows[keyId] }));
  }

  fingerprintLabel(item: AccessKeyRecord): string {
    return this.visibleRows()[item.id] ? obfuscateFingerprint(item.fingerprint) : MASKED_KEY_LABEL;
  }

  lastUsedLabel(item: AccessKeyRecord): string {
    return formatTimestamp(item.last_used_at);
  }

  activateActionLabel(item: AccessKeyRecord): string {
    return item.is_active ? 'Key is active' : 'Activate key';
  }

  visibilityActionLabel(item: AccessKeyRecord): string {
    return this.visibleRows()[item.id] ? 'Hide fingerprint' : 'Show fingerprint';
  }
}



<app-modal-shell (close)="closed.emit()"
  [isOpen]="isOpen"
  [title]="providerLabel + ' Access Keys'"
  subtitle="Stored encrypted at rest. New keys remain inactive until you explicitly activate one."
  dialogClassName="modal-container access-key-modal"
  closeLabel="Close access key modal"
>
  <section class="modal-section">
    <h3 class="modal-section-title">Add New Key</h3>
    <div class="access-key-input-row">
      <label class="visually-hidden" for="new-access-key-input">Access key</label>
      <input
        id="new-access-key-input"
        class="access-key-input"
        type="password"
        placeholder="Paste access key"
        [ngModel]="newKeyValue()"
        (ngModelChange)="newKeyValue.set($event)"
        [disabled]="isSaving()"
      />
      <button class="btn btn-primary access-key-add-btn" type="button" (click)="addKey()" [disabled]="isSaving()">
        Add
      </button>
    </div>
  </section>

  <section class="modal-section">
    <h3 class="modal-section-title">Stored Keys</h3>
    @if (isLoading()) {
      <p class="access-key-empty">Loading keys...</p>
    }
    @if (!isLoading() && !hasKeys()) {
      <p class="access-key-empty">No keys stored for this provider.</p>
    }
    @if (!isLoading() && hasKeys()) {
      <ul class="access-key-list">
        @for (item of sortedKeys(); track item.id) {
          <li class="access-key-row" [class.is-active]="item.is_active">
            <div class="access-key-meta">
              <div class="access-key-meta-top">
                <p class="access-key-fingerprint">{{ fingerprintLabel(item) }}</p>
                @if (item.is_active) {
                  <span class="access-key-state">Active</span>
                }
              </div>
              <p class="access-key-timestamp">Last used: {{ lastUsedLabel(item) }}</p>
            </div>
            <div class="access-key-actions">
              <button
                class="access-key-action"
                [class.is-active]="item.is_active"
                type="button"
                (click)="activateKey(item.id)"
                [disabled]="isSaving() || item.is_active"
                [attr.aria-label]="activateActionLabel(item)"
                [title]="activateActionLabel(item)"
              >
                <svg viewBox="0 0 24 24" aria-hidden="true">
                  <path d="m5 12.5 4.2 4.2L19 7" />
                </svg>
              </button>
              <button
                class="access-key-action"
                type="button"
                (click)="toggleVisibility(item.id)"
                [disabled]="isSaving()"
                [attr.aria-label]="visibilityActionLabel(item)"
                [title]="visibilityActionLabel(item)"
              >
                @if (visibleRows()[item.id]) {
                  <svg viewBox="0 0 24 24" aria-hidden="true">
                    <path d="m3 3 18 18" />
                    <path d="M10.58 10.58a2 2 0 0 0 2.84 2.84" />
                    <path d="M9.88 5.09A10.94 10.94 0 0 1 12 4.91c5.27 0 9.27 4.24 10 7.09-.26 1.02-.92 2.32-1.98 3.56" />
                    <path d="M6.23 6.23C4.17 7.65 2.75 9.74 2 12c.73 2.85 4.73 7.09 10 7.09 1.76 0 3.35-.47 4.74-1.17" />
                  </svg>
                } @else {
                  <svg viewBox="0 0 24 24" aria-hidden="true">
                    <path d="M2 12c.73-2.85 4.73-7.09 10-7.09S21.27 9.15 22 12c-.73 2.85-4.73 7.09-10 7.09S2.73 14.85 2 12Z" />
                    <circle cx="12" cy="12" r="3" />
                  </svg>
                }
              </button>
              <button
                class="access-key-action is-danger"
                type="button"
                (click)="deleteKey(item.id)"
                [disabled]="isSaving()"
                aria-label="Delete key"
                title="Delete key"
              >
                <svg viewBox="0 0 24 24" aria-hidden="true">
                  <path d="M4 7h16" />
                  <path d="M9 7V5.75A1.75 1.75 0 0 1 10.75 4h2.5A1.75 1.75 0 0 1 15 5.75V7" />
                  <path d="M6.5 7 7.3 19a2 2 0 0 0 2 1.86h5.4a2 2 0 0 0 2-1.86L17.5 7" />
                  <path d="M10 11v5M14 11v5" />
                </svg>
              </button>
            </div>
          </li>
        }
      </ul>
    }
  </section>

  <app-status-message [message]="errorMessage() ? '[ERROR] ' + errorMessage() : ''" tone="is-error"></app-status-message>
</app-modal-shell>
