// DILIGENT/client/src/components/NavSidebar.tsx
import React from "react";
import { PageId, useAppState } from "../context/AppStateContext";

// ---------------------------------------------------------------------------
// Icon Components
// ---------------------------------------------------------------------------
const DiligentLogo = () => (
    <svg
        viewBox="0 0 120 36"
        role="img"
        aria-labelledby="diligent-logo-title"
    >
        <title id="diligent-logo-title">Application logo</title>
        <rect x="2" y="2" width="32" height="32" rx="8" fill="rgba(22, 163, 74, 0.24)" />
        <path
            d="M10 26V10h6.5c6 0 9.5 3.1 9.5 8s-3.5 8-9.5 8H10zm5-4h1.2c3.2 0 5-1.3 5-4s-1.8-4-5-4H15v8z"
            fill="#4ade80"
        />
        <text x="42" y="16" fill="currentColor" fontSize="10" fontWeight="800" letterSpacing="0.14em">
            DILIGENT
        </text>
        <text x="42" y="27" fill="currentColor" fillOpacity="0.78" fontSize="7.5" fontWeight="600" letterSpacing="0.08em">
            CLINICAL COPILOT
        </text>
    </svg>
);

const AgentIcon = () => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
        <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" />
        <line x1="9" y1="10" x2="15" y2="10" />
    </svg>
);

const DataIcon = () => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
        <ellipse cx="12" cy="6" rx="7" ry="3" />
        <path d="M5 6v6c0 1.66 3.13 3 7 3s7-1.34 7-3V6" />
        <path d="M5 12v6c0 1.66 3.13 3 7 3s7-1.34 7-3v-6" />
    </svg>
);

const SettingsIcon = () => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
        <circle cx="12" cy="12" r="3" />
        <path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z" />
    </svg>
);

// ---------------------------------------------------------------------------
// NavItem
// ---------------------------------------------------------------------------
interface NavItemProps {
    pageId: PageId;
    icon: React.ReactNode;
    label: string;
    isActive: boolean;
    onClick: (pageId: PageId) => void;
}

function NavItem({ pageId, icon, label, isActive, onClick }: NavItemProps): React.JSX.Element {
    return (
        <button
            type="button"
            className={`tab-item ${isActive ? "active" : ""}`}
            onClick={() => onClick(pageId)}
            aria-current={isActive ? "page" : undefined}
            title={label}
        >
            <span className="tab-icon">{icon}</span>
            <span className="tab-label">{label}</span>
        </button>
    );
}

// ---------------------------------------------------------------------------
// NavTabs
// ---------------------------------------------------------------------------
interface NavTabsProps {
    onNavigate: (pageId: PageId) => void;
}

export function NavTabs({ onNavigate }: NavTabsProps): React.JSX.Element {
    const { state, toggleTheme } = useAppState();

    const navItems: { pageId: PageId; icon: React.ReactNode; label: string }[] = [
        { pageId: "dili-agent", icon: <AgentIcon />, label: "DILI Agent" },
        { pageId: "data-inspection", icon: <DataIcon />, label: "Data Inspection" },
        { pageId: "model-config", icon: <SettingsIcon />, label: "Model Configurations" },
    ];

    return (
        <div className="app-top-nav">
            <header className="app-header">
                <div className="app-header-brand">
                    <span className="app-header-logo">
                        <DiligentLogo />
                    </span>
                    <div className="app-theme-toggle">
                        <span className="app-theme-toggle-label">Dark mode</span>
                        <label className="toggle-switch">
                            <span className="visually-hidden">Toggle dark mode</span>
                            <input
                                type="checkbox"
                                checked={state.theme === "dark"}
                                onChange={toggleTheme}
                                aria-label="Toggle dark mode"
                            />
                            <span className="toggle-track" aria-hidden="true">
                                <span className="toggle-thumb" />
                            </span>
                        </label>
                    </div>
                </div>
            </header>
            <nav className="tab-bar" aria-label="Main navigation">
                <div className="tab-items">
                    {navItems.map((item) => (
                        <NavItem
                            key={item.pageId}
                            pageId={item.pageId}
                            icon={item.icon}
                            label={item.label}
                            isActive={state.activePage === item.pageId}
                            onClick={onNavigate}
                        />
                    ))}
                </div>
            </nav>
        </div>
    );
}

// DILIGENT/client/src/app/components/nav-sidebar/nav-sidebar.component.ts
import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Output, inject } from '@angular/core';

import { AppStateService, PageId } from '../../core/state/app-state.service';

@Component({
  selector: 'app-nav-sidebar',
  imports: [CommonModule],
  templateUrl: './nav-sidebar.component.html',
  styleUrl: './nav-sidebar.component.scss',
})
export class NavSidebarComponent {
  @Output() navigate = new EventEmitter<PageId>();

  readonly stateService = inject(AppStateService);

  readonly navItems: Array<{ pageId: PageId; label: string }> = [
    { pageId: 'dili-agent', label: 'DILI Agent' },
    { pageId: 'data-inspection', label: 'Data Inspection' },
    { pageId: 'model-config', label: 'Model Configurations' },
  ];

  onNavigate(pageId: PageId): void {
    this.navigate.emit(pageId);
  }

  toggleTheme(): void {
    this.stateService.toggleTheme();
  }

  get isDarkTheme(): boolean {
    return this.stateService.state().theme === 'dark';
  }

  get themeAriaLabel(): string {
    return this.isDarkTheme ? 'Switch to light theme' : 'Switch to dark theme';
  }
}

<div class="app-top-nav">
  <header class="app-header">
    <div class="app-header-content">
      <div class="app-header-brand">
        <span class="app-header-logo">
          <img src="/diligent-logo.png" alt="Diligent logo" />
        </span>
        <span class="app-header-wordmark">Diligent</span>
      </div>
      <nav class="tab-bar" aria-label="Main navigation">
        <div class="tab-items">
          @for (item of navItems; track item.pageId) {
            <button
              type="button"
              class="tab-item"
              [class.active]="stateService.state().activePage === item.pageId"
              (click)="onNavigate(item.pageId)"
              [attr.aria-current]="stateService.state().activePage === item.pageId ? 'page' : null"
              [title]="item.label"
            >
              <span class="tab-label">{{ item.label }}</span>
            </button>
          }
        </div>
      </nav>
      <div class="app-header-actions">
        <button
          type="button"
          class="app-header-icon-btn"
          (click)="toggleTheme()"
          [attr.aria-label]="themeAriaLabel"
          [attr.title]="themeAriaLabel"
        >
          @if (isDarkTheme) {
            <svg class="theme-icon" viewBox="0 0 24 24" aria-hidden="true">
              <path fill="currentColor" d="M12 18a6 6 0 1 1 0-12 6 6 0 0 1 0 12Zm0-16a1 1 0 0 1 1 1v2a1 1 0 1 1-2 0V3a1 1 0 0 1 1-1Zm0 17a1 1 0 0 1 1 1v2a1 1 0 1 1-2 0v-2a1 1 0 0 1 1-1ZM3 11a1 1 0 1 1 0 2H1a1 1 0 1 1 0-2h2Zm20 0a1 1 0 1 1 0 2h-2a1 1 0 1 1 0-2h2ZM5.64 4.22a1 1 0 0 1 1.41 0l1.42 1.42a1 1 0 0 1-1.42 1.41L5.64 5.64a1 1 0 0 1 0-1.42Zm12.73 12.73a1 1 0 0 1 1.41 0l1.42 1.42a1 1 0 0 1-1.42 1.41l-1.41-1.41a1 1 0 0 1 0-1.42ZM4.22 18.36a1 1 0 0 1 0-1.41l1.42-1.42a1 1 0 0 1 1.41 1.42l-1.41 1.41a1 1 0 0 1-1.42 0Zm12.73-12.73a1 1 0 0 1 0-1.41l1.42-1.42a1 1 0 0 1 1.41 1.42l-1.41 1.41a1 1 0 0 1-1.42 0Z"/>
            </svg>
          } @else {
            <svg class="theme-icon" viewBox="0 0 24 24" aria-hidden="true">
              <path fill="currentColor" d="M21 13.02A9 9 0 1 1 10.98 3a1 1 0 0 1 .9 1.42A7 7 0 0 0 19.58 12a6.9 6.9 0 0 0 .01.37 1 1 0 0 1 1.41.65ZM12 21a7 7 0 0 0 6.97-6.34A9.06 9.06 0 0 1 9.34 5.03 7 7 0 0 0 12 21Z"/>
            </svg>
          }
        </button>
      </div>
    </div>
  </header>
</div>
