// app/client/src/app/pages/dili-agent/dili-agent-page.component.ts
import { CommonModule } from '@angular/common';
import { Component, ElementRef, HostListener, OnDestroy, ViewChild, computed, effect, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';

import { DEFAULT_FORM_STATE, REPORT_EXPORT_FILENAME } from '../../core/constants';
import { AppStateService } from '../../core/state/app-state.service';
import {
  buildClinicalPayload,
  createDownloadUrl,
  formatErrorMessage,
  formatUnknownError,
  normalizeVisitDateInput,
} from '../../core/utils';
import {
  JobStatus,
  JobStatusResponse,
} from '../../core/models/types';
import {
  fetchClinicalSectionTemplate,
  cancelClinicalJob,
  pollClinicalJobStatus,
  resolvePollIntervalMs,
  startClinicalJob,
} from '../../core/services/clinical-api';
import { MarkdownRendererService } from '../../core/services/markdown-renderer.service';

const todayIso = new Date().toISOString().slice(0, 10);
const STAGE_FALLBACK_LABELS: Record<string, string> = {
  session_initialization: 'Step 1/12 - Initializing session context and validating clinical inputs',
  therapy_extraction: 'Step 2/12 - Parsing THERAPY section to extract active treatment lines',
  anamnesis_extraction: 'Step 3/12 - Parsing ANAMNESIS section to identify historical drug exposures',
  anamnesis_disease_extraction: 'Step 4/12 - Parsing ANAMNESIS section to extract comorbidities and risk context',
  anamnesis_lab_extraction: 'Step 5/12 - Parsing LAB ANALYSIS history to reconstruct longitudinal trends',
  hepatotoxicity_pattern: 'Step 6/12 - Computing hepatotoxicity pattern from laboratory trajectory',
  rag_query_building: 'Step 7/12 - Preparing evidence-retrieval query context',
  livertox_lookup: 'Step 8/12 - Cross-checking candidate drugs against LiverTox evidence',
  rucam_estimation: 'Step 9/12 - Estimating per-drug RUCAM scores',
  llm_analysis: 'Step 10/12 - Performing structured LLM causality assessment per candidate drug',
  report_composition: 'Step 11/12 - Drafting integrated clinical assessment and recommendations',
  finalization: 'Step 12/12 - Final consistency checks and session persistence',
};

function isTerminalJobStatus(status: JobStatus | null): boolean {
  return status === 'completed' || status === 'failed' || status === 'cancelled';
}

@Component({
  selector: 'app-dili-agent-page',
  imports: [CommonModule, FormsModule],
  templateUrl: './dili-agent-page.component.html',
  styleUrl: './dili-agent-page.component.scss',
})
export class DiliAgentPageComponent implements OnDestroy {
  @ViewChild('patientImageInput') private patientImageInput?: ElementRef<HTMLInputElement>;

  readonly stateService = inject(AppStateService);
  private readonly markdownRenderer = inject(MarkdownRendererService);

  readonly isCancelling = signal(false);
  readonly isRunActionLocked = signal(false);
  readonly todayIso = todayIso;
  readonly finalReportMarkdown = computed(() => this.stateService.state().diliAgent.message || this.reportBody);
  readonly renderedReport = computed(() => this.markdownRenderer.render(this.finalReportMarkdown()));
  readonly clinicalInputTemplate = signal('');

  private poller: { stop: () => void } | null = null;
  private runActionLockTimer: ReturnType<typeof globalThis.setTimeout> | null = null;
  private runControlDebounceTimer: ReturnType<typeof globalThis.setTimeout> | null = null;
  private runControlDebounced = false;

  constructor() {
    void this.loadClinicalSectionTemplate();
    effect(() => {
      const state = this.vm;
      if (
        state.jobStatus === 'completed' &&
        state.message &&
        !state.exportUrl &&
        !state.isRunning &&
        !state.isStarting
      ) {
        const restoredExportUrl = createDownloadUrl(state.message, REPORT_EXPORT_FILENAME);
        this.stateService.updateDiliAgent({ exportUrl: restoredExportUrl });
      }
    });
  }

  get vm() {
    return this.stateService.state().diliAgent;
  }

  ngOnDestroy(): void {
    this.stopPoller();
    this.clearRunActionLock();
    if (this.runControlDebounceTimer !== null) {
      globalThis.clearTimeout(this.runControlDebounceTimer);
      this.runControlDebounceTimer = null;
    }
    this.revokeObjectUrl();
  }

  handleFormChange<K extends keyof typeof this.vm.form>(key: K, value: (typeof this.vm.form)[K]): void {
    const currentMessage = this.vm.message ?? '';
    const shouldClearStaleOutput =
      !this.vm.isRunning &&
      !this.vm.isStarting &&
      Boolean(currentMessage || this.vm.exportUrl || this.vm.jobId || this.vm.jobStatus);
    const shouldClearValidationMessage =
      !this.vm.isRunning &&
      !this.vm.isStarting &&
      currentMessage.startsWith('[ERROR]') &&
      currentMessage !== '[ERROR] Clinical analysis failed.';

    if (shouldClearStaleOutput && this.vm.exportUrl) {
      this.revokeObjectUrl();
    }
    this.stateService.updateDiliAgent({
      form: {
        ...this.vm.form,
        [key]: value,
      },
      ...(shouldClearStaleOutput || shouldClearValidationMessage
        ? {
            message: '',
            exportUrl: null,
            jobId: null,
            jobProgress: 0,
            jobStatus: null,
            jobStage: null,
            jobStageMessage: null,
          }
        : {}),
    });
  }

  private async loadClinicalSectionTemplate(): Promise<void> {
    try {
      const response = await fetchClinicalSectionTemplate();
      if (response.template?.trim()) {
        this.clinicalInputTemplate.set(response.template.trim());
        return;
      }
    } catch {
      this.clinicalInputTemplate.set('');
    }
  }

  handleVisitDateChange(value: string): void {
    this.handleFormChange('visitDate', normalizeVisitDateInput(value));
  }

  openPatientImagePicker(): void {
    this.patientImageInput?.nativeElement.click();
  }

  handlePatientImageSelection(event: Event): void {
    const target = event.target;
    if (!(target instanceof HTMLInputElement)) {
      return;
    }
    const file = target.files?.[0];
    if (!file) {
      return;
    }
    const reader = new FileReader();
    reader.onload = () => {
      const dataUrl = typeof reader.result === 'string' ? reader.result : null;
      this.handleFormChange('patientImageDataUrl', dataUrl);
    };
    reader.readAsDataURL(file);
  }

  private revokeObjectUrl(): void {
    if (this.vm.exportUrl) {
      URL.revokeObjectURL(this.vm.exportUrl);
    }
  }

  private resetOutputs(): void {
    this.revokeObjectUrl();
    this.stateService.updateDiliAgent({
      message: '',
      exportUrl: null,
      jobId: null,
      jobProgress: 0,
      jobStatus: null,
      jobStage: null,
      jobStageMessage: null,
    });
  }

  private stopPoller(): void {
    if (this.poller) {
      this.poller.stop();
      this.poller = null;
    }
  }

  private onPollingError(pollError: string): void {
    this.stopPoller();
    this.isCancelling.set(false);
    this.stateService.updateDiliAgent({
      message: formatErrorMessage(pollError),
      exportUrl: null,
      jobStage: null,
      jobStageMessage: null,
      isStarting: false,
      isRunning: false,
    });
  }

  private clearRunActionLock(): void {
    if (this.runActionLockTimer !== null) {
      globalThis.clearTimeout(this.runActionLockTimer);
      this.runActionLockTimer = null;
    }
    this.isRunActionLocked.set(false);
  }

  private lockRunAction(windowMs: number = 1750): void {
    this.clearRunActionLock();
    this.isRunActionLocked.set(true);
    this.runActionLockTimer = globalThis.setTimeout(() => {
      this.runActionLockTimer = null;
      this.isRunActionLocked.set(false);
    }, Math.max(500, windowMs));
  }

  private onJobStatusUpdate(status: JobStatusResponse): void {
    const terminalStatus = isTerminalJobStatus(status.status);
    const stage =
      status.result && typeof status.result.progress_stage === 'string'
        ? status.result.progress_stage
        : null;
    const stageMessage =
      status.result && typeof status.result.progress_message === 'string'
        ? status.result.progress_message
        : null;
    const resolvedProgress = typeof status.progress === 'number' ? status.progress : 0;

    this.stateService.updateDiliAgent({
      jobProgress: terminalStatus ? 100 : resolvedProgress,
      jobStatus: status.status,
      jobStage: stage,
      jobStageMessage: stageMessage,
      isStarting: false,
      isRunning: !terminalStatus,
    });

    if (!terminalStatus) {
      return;
    }

    this.stopPoller();
    this.isCancelling.set(false);

    if (status.status === 'completed') {
      const report = typeof status.result?.report === 'string' ? status.result.report : '';
      const newExportUrl = report ? createDownloadUrl(report, REPORT_EXPORT_FILENAME) : null;
      this.stateService.updateDiliAgent({
        message: report || '[INFO] Clinical analysis completed.',
        exportUrl: newExportUrl,
        jobStage: null,
        jobStageMessage: null,
      });
    } else if (status.status === 'failed') {
      const errorMessage = status.error
        ? formatErrorMessage(status.error)
        : '[ERROR] Clinical analysis failed.';
      this.stateService.updateDiliAgent({
        message: errorMessage,
        exportUrl: null,
        jobStage: null,
        jobStageMessage: null,
      });
    } else if (status.status === 'cancelled') {
      this.stateService.updateDiliAgent({
        message: '[INFO] Clinical analysis cancelled.',
        exportUrl: null,
        jobStage: null,
        jobStageMessage: null,
      });
    }
  }

  private startPolling(jobIdToPoll: string, intervalMs: number): void {
    this.stopPoller();
    this.poller = pollClinicalJobStatus(
      jobIdToPoll,
      intervalMs,
      (status) => this.onJobStatusUpdate(status),
      (message) => this.onPollingError(message),
    );
  }

  private async executeRunSession(): Promise<void> {
    if (this.vm.isStarting || this.vm.isRunning || this.isRunActionLocked()) {
      return;
    }
    this.lockRunAction();
    this.isCancelling.set(false);
    this.stateService.updateDiliAgent({ isStarting: true, isRunning: true });
    this.resetOutputs();
    this.stopPoller();

    try {
      const payload = buildClinicalPayload(this.vm.form, this.vm.settings);
      const startResult = await startClinicalJob(payload);
      this.stateService.updateDiliAgent({
        jobId: startResult.job_id,
        jobProgress: 0,
        jobStatus: startResult.status,
        jobStage: 'session_initialization',
        jobStageMessage: STAGE_FALLBACK_LABELS['session_initialization'],
        isStarting: false,
      });
      const intervalMs = resolvePollIntervalMs(startResult.poll_interval);
      this.startPolling(startResult.job_id, intervalMs);
    } catch (error) {
      this.stateService.updateDiliAgent({
        message: formatUnknownError(error, 'Unexpected error'),
        exportUrl: null,
        jobStage: null,
        jobStageMessage: null,
        isStarting: false,
        isRunning: false,
      });
    }
  }

  async runSession(): Promise<void> {
    const message = this.validationMessage();
    if (message) {
      this.resetOutputs();
      this.stateService.updateDiliAgent({
        isRunning: false,
        message,
      });
      return;
    }

    await this.executeRunSession();
  }

  async stopSession(): Promise<void> {
    if (this.vm.isStarting && !this.vm.jobId) {
      return;
    }
    if (!this.vm.jobId) {
      return;
    }
    this.lockRunAction(5000);
    this.isCancelling.set(true);
    try {
      await cancelClinicalJob(this.vm.jobId);
      this.stateService.updateDiliAgent({
        message: '[INFO] Cancellation requested. Waiting for worker shutdown...',
      });
    } catch (error) {
      this.stateService.updateDiliAgent({
        message: formatUnknownError(error, 'Failed to request cancellation.'),
      });
    } finally {
      this.isCancelling.set(false);
    }
  }

  clearAll(): void {
    this.revokeObjectUrl();
    this.stateService.updateDiliAgent({
      form: { ...DEFAULT_FORM_STATE },
      message: '',
      exportUrl: null,
      jobId: null,
      jobProgress: 0,
      jobStatus: null,
      jobStage: null,
      jobStageMessage: null,
      isStarting: false,
    });
  }

  async copyReport(): Promise<void> {
    const rendered = this.renderedReport();
    if (!rendered.text) {
      return;
    }
    const clipboardItemCtor = (globalThis as { ClipboardItem?: typeof ClipboardItem }).ClipboardItem;
    if (navigator.clipboard && clipboardItemCtor) {
      const item = new clipboardItemCtor({
        'text/html': new Blob([rendered.html], { type: 'text/html' }),
        'text/plain': new Blob([rendered.text], { type: 'text/plain' }),
      });
      await navigator.clipboard.write([item]);
      return;
    }
    if (navigator.clipboard) {
      await navigator.clipboard.writeText(rendered.text);
    }
  }

  toggleReportExpanded(): void {
    this.stateService.updateDiliAgent({ isExpanded: !this.vm.isExpanded });
  }

  collapseReport(): void {
    this.stateService.updateDiliAgent({ isExpanded: false });
  }

  downloadReport(): void {
    if (!this.vm.exportUrl) return;
    const anchor = document.createElement('a');
    anchor.href = this.vm.exportUrl;
    anchor.download = REPORT_EXPORT_FILENAME;
    anchor.click();
  }

  @HostListener('document:keydown.escape')
  onEscape(): void {
    if (this.vm.isExpanded) {
      this.collapseReport();
    }
  }

  runOrStop(): void {
    if (this.isCancelling()) {
      return;
    }
    if (this.vm.isRunning) {
      void this.stopSession();
      return;
    }
    if (this.runControlDebounced) {
      return;
    }
    if (this.vm.isStarting || this.isRunActionLocked()) {
      return;
    }
    this.runControlDebounced = true;
    if (this.runControlDebounceTimer !== null) {
      globalThis.clearTimeout(this.runControlDebounceTimer);
    }
    this.runControlDebounceTimer = globalThis.setTimeout(() => {
      this.runControlDebounced = false;
      this.runControlDebounceTimer = null;
    }, 1000);
    void this.runSession();
  }

  get showSpinner(): boolean {
    return this.vm.isRunning && !isTerminalJobStatus(this.vm.jobStatus);
  }

  get spinnerStatusLabel(): string {
    const baseLabel = this.vm.jobStageMessage
      || (this.vm.jobStage ? STAGE_FALLBACK_LABELS[this.vm.jobStage] : null)
      || 'Starting clinical analysis';
    const suffix = this.vm.jobProgress > 0
      ? `... ${this.vm.jobProgress.toFixed(0)}%`
      : '...';
    return `${baseLabel}${suffix}`;
  }

  get runActionDisabled(): boolean {
    if (this.vm.isRunning) {
      return this.isCancelling();
    }
    return this.isCancelling()
      || this.vm.isStarting
      || this.isRunActionLocked()
      || !this.canStartSession();
  }

  get runActionLabel(): string {
    if (!this.vm.isRunning) {
      return 'Run DILI analysis';
    }
    if (this.isCancelling()) {
      return 'Stopping...';
    }
    if (!this.vm.jobId) {
      return 'Starting...';
    }
    return 'Stop analysis';
  }

  get runDisabledReason(): string | null {
    if (this.vm.isRunning || this.vm.isStarting || this.isCancelling()) {
      return null;
    }
    if (!this.vm.form.visitDate.trim()) {
      return 'Add a visit date to run analysis.';
    }
    if (!this.vm.form.clinicalInput.trim()) {
      return 'Add the clinical input to run analysis.';
    }
    if (!this.clinicalInputMeetsMinimumLength()) {
      return 'Clinical input needs at least 60 words.';
    }
    if (!this.hasSelectedModelProvider()) {
      return 'Select a model provider to run analysis.';
    }
    return null;
  }

  get reportBody(): string {
    return this.vm.message || 'No report generated yet. Run analysis to see results.';
  }

  get patientNameLabel(): string {
    return this.vm.form.patientName.trim() || 'Unnamed patient';
  }

  get patientImageDataUrl(): string | null {
    return this.vm.form.patientImageDataUrl;
  }

  get recordedDateLabel(): string {
    if (!this.vm.form.visitDate) {
      return 'Not set';
    }
    return new Date(`${this.vm.form.visitDate}T00:00:00`).toLocaleDateString(undefined, {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
  }

  private countClinicalWords(value: string): number {
    const matches = value.match(/\b[\wÀ-ÖØ-öø-ÿ']+\b/gu);
    return matches ? matches.length : 0;
  }

  private selectedModelProviders(): string[] {
    const provider = this.vm.settings.provider?.trim();
    return provider ? [provider] : [];
  }

  private clinicalInputMeetsMinimumLength(): boolean {
    return this.countClinicalWords(this.vm.form.clinicalInput.trim()) >= 60;
  }

  private hasSelectedModelProvider(): boolean {
    return this.selectedModelProviders().length > 0;
  }

  canStartSession(): boolean {
    return Boolean(this.vm.form.visitDate.trim())
      && Boolean(this.vm.form.clinicalInput.trim())
      && this.clinicalInputMeetsMinimumLength()
      && this.hasSelectedModelProvider();
  }

  validationMessage(): string | null {
    if (!this.vm.form.visitDate.trim()) {
      return '[ERROR] Provide the visit date.';
    }
    if (!this.vm.form.clinicalInput.trim()) {
      return '[ERROR] Provide the clinical input.';
    }
    if (!this.clinicalInputMeetsMinimumLength()) {
      return '[ERROR] Clinical input must contain at least 60 words.';
    }
    if (!this.hasSelectedModelProvider()) {
      return '[ERROR] Select at least one model provider.';
    }
    return null;
  }
}

<main class="page-container stitch-dili-page">
  <div class="stitch-dili-grid">
    <section class="stitch-dili-main stitch-dili-workbench">
      <div class="stitch-dili-input-grid">
        <div class="stitch-dili-input-group stitch-dili-input-group--wide">
          <h3>
            <svg class="stitch-dili-label-icon" viewBox="0 0 24 24" aria-hidden="true">
              <path
                fill="currentColor"
                d="M7 2.75A2.75 2.75 0 0 0 4.25 5.5v13A2.75 2.75 0 0 0 7 21.25h10A2.75 2.75 0 0 0 19.75 18.5v-8.9a2.75 2.75 0 0 0-.807-1.943l-4.6-4.6A2.75 2.75 0 0 0 12.4 2.75H7Zm5.05 1.5 4.45 4.45c.16.16.26.36.3.57H13A1.25 1.25 0 0 1 11.75 8V4.26c.12.02.23.06.3.12ZM7 4.25h3.25V8A2.75 2.75 0 0 0 13 10.75h3.75v7.75A1.25 1.25 0 0 1 15.5 19.75H7a1.25 1.25 0 0 1-1.25-1.25v-13A1.25 1.25 0 0 1 7 4.25Z"
              />
            </svg>
            Clinical Input
          </h3>
          <textarea
            id="clinical-input"
            data-guidance-target="dili-clinical-input"
            aria-label="Clinical Input"
            class="stitch-dili-input-unified"
            [placeholder]="clinicalInputTemplate()"
            [ngModel]="vm.form.clinicalInput"
            (ngModelChange)="handleFormChange('clinicalInput', $event)"
          ></textarea>
        </div>
      </div>
    </section>

    <aside class="stitch-dili-sidebar">
      <section class="stitch-dili-patient">
        <div class="stitch-dili-patient-top">
          <button
            type="button"
            class="stitch-dili-avatar stitch-dili-avatar-button"
            (click)="openPatientImagePicker()"
            aria-label="Upload patient profile image"
            title="Upload patient profile image"
          >
            @if (patientImageDataUrl) {
              <img [src]="patientImageDataUrl" alt="Patient profile preview" class="stitch-dili-avatar-image" />
            } @else {
              <span aria-hidden="true">{{ patientNameLabel.charAt(0).toUpperCase() }}</span>
            }
          </button>
          <input
            #patientImageInput
            type="file"
            accept="image/*"
            class="inspection-folder-input"
            aria-label="Patient profile image file picker"
            (change)="handlePatientImageSelection($event)"
          />
          <div>
            <h3>{{ patientNameLabel }}</h3>
            <p>Recorded: {{ recordedDateLabel }}</p>
          </div>
        </div>

        <div class="stitch-dili-inline-fields">
          <div class="field">
            <label class="field-label" for="patient-name">Patient Name</label>
            <input
              id="patient-name"
              type="text"
              placeholder="e.g., Marco Rossi"
              [ngModel]="vm.form.patientName"
              (ngModelChange)="handleFormChange('patientName', $event)"
            />
          </div>
          <div class="field">
            <label class="field-label" for="visit-date">Visit Date</label>
            <input
              id="visit-date"
              type="date"
              lang="en-CA"
              [max]="todayIso"
              [ngModel]="vm.form.visitDate"
              (ngModelChange)="handleVisitDateChange($event)"
            />
          </div>
        </div>

        <label class="stitch-dili-rag-toggle" for="rag-enabled" data-guidance-target="dili-rag-toggle">
          <input
            id="rag-enabled"
            type="checkbox"
            [ngModel]="vm.form.useRag"
            (ngModelChange)="handleFormChange('useRag', $event)"
            [disabled]="vm.isRunning || vm.isStarting"
          />
          <span>
            <strong>Use RAG evidence</strong>
            <small>Retrieve indexed source documents and include compact bibliography references.</small>
          </span>
        </label>

        <div class="stitch-dili-actions">
          <button
            #runAnalysisButton
            id="run-analysis-button"
            data-guidance-target="dili-run-action"
            class="btn btn-primary"
            type="button"
            [disabled]="runActionDisabled"
            (click)="runOrStop()"
          >
            {{ runActionLabel }}
          </button>
          <div class="stitch-dili-clear-container">
            <button class="stitch-dili-clear" type="button" (click)="clearAll()" [disabled]="vm.isRunning">
              Clear all
            </button>
          </div>
        </div>
      </section>

    </aside>
  </div>

  <section class="report-section stitch-dili-report">
    <div class="report-shell stitch-dili-report-shell" [class.is-full-page]="vm.isExpanded" [attr.aria-expanded]="vm.isExpanded">
      <div class="report-toolbar">
        <p class="report-toolbar-label">DILI Assessment</p>
        <button class="toolbar-btn" type="button" (click)="copyReport()" [disabled]="!vm.exportUrl">
          Copy
        </button>
        @if (vm.isExpanded) {
          <button class="toolbar-btn" type="button" (click)="collapseReport()" [disabled]="!vm.exportUrl">Collapse</button>
        } @else {
          <button class="toolbar-btn" type="button" (click)="toggleReportExpanded()" [disabled]="!vm.exportUrl">Expand</button>
        }
        <button class="toolbar-btn" type="button" (click)="downloadReport()" [disabled]="!vm.exportUrl">
          Download report
        </button>
      </div>

      <div class="report-content" [class.is-expanded]="vm.isExpanded">
        @if (showSpinner) {
          <div class="session-spinner" role="status" aria-live="polite">
            <div class="spinner-wheel"></div>
            <p class="spinner-label">
              {{ spinnerStatusLabel }}
            </p>
          </div>
        } @else {
          <article id="rendered-report-content" class="report-markdown inspection-excerpt-text" [innerHTML]="renderedReport().html"></article>
          @if (!vm.message && !vm.isRunning && !vm.isStarting) {
            <app-feature-tip
              [guidanceId]="'dili-first-assessment'"
              [version]="guidanceDefinitions.diliFirstAssessment.version"
              [title]="guidanceDefinitions.diliFirstAssessment.title"
              [body]="guidanceDefinitions.diliFirstAssessment.description"
              actionLabel="Show me"
              secondaryLabel="Open Configurations"
              (primaryAction)="startAssessmentTour()"
              (secondaryAction)="openConfigurations()"
            ></app-feature-tip>
          }
        }
      </div>
    </div>
  </section>
</main>

<app-modal-shell
  [isOpen]="preflightDialog() !== null"
  [title]="preflightHasBlockingIssues() ? 'Cannot start analysis' : 'Review before continuing'"
  titleId="preflight-title"
  ariaLabelledBy="preflight-title"
  ariaDescribedBy="preflight-description"
  dialogClassName="modal-container preflight-modal"
  closeLabel="Return to clinical input"
  [footer]="true"
  [showCloseButton]="!preflightHasBlockingIssues()"
  [closeOnEscape]="!preflightHasBlockingIssues()"
  [restoreFocus]="false"
  (close)="returnToInputFromPreflight()"
  (closed)="focusPreflightTarget()"
>
  <section class="preflight-modal-content">
    <div class="preflight-introduction">
      <p id="preflight-description">
        @if (preflightHasBlockingIssues()) {
          Correct the blocking items below before starting the analysis.
        } @else {
          The analysis can continue, but the listed limitations may reduce its completeness or reliability.
        }
      </p>
      <div class="preflight-summary" aria-label="Pre-flight issue summary">
        @if (preflightBlockingCount()) {
          <span class="preflight-summary-badge is-blocking">
            {{ preflightBlockingCount() }} blocking
          </span>
        }
        @if (preflightWarningCount()) {
          <span class="preflight-summary-badge is-warning">
            {{ preflightWarningCount() }} warning{{ preflightWarningCount() === 1 ? '' : 's' }}
          </span>
        }
      </div>
    </div>

    <div class="preflight-issue-list" data-testid="preflight-issue-list" tabindex="0">
      @for (issue of preflightIssues(); track issue.code + '-' + $index) {
        <article
          class="preflight-issue"
          [class.is-blocking]="issue.severity === 'blocking'"
          [class.is-warning]="issue.severity === 'non_blocking'"
        >
          <div class="preflight-issue-heading">
            <span class="preflight-severity">
              {{ issue.severity === 'blocking' ? 'Blocking' : 'Warning' }}
            </span>
            <h3>{{ issue.title }}</h3>
          </div>
          <dl>
            <div>
              <dt>Affected section</dt>
              <dd>{{ issue.affected_section }}</dd>
            </div>
            <div>
              <dt>What needs attention</dt>
              <dd>{{ issue.description }}</dd>
            </div>
            <div>
              <dt>Consequence</dt>
              <dd>{{ issue.consequence }}</dd>
            </div>
          </dl>
        </article>
      }
    </div>
  </section>

  <div modal-footer class="preflight-actions">
    <button
      class="btn btn-secondary"
      type="button"
      data-modal-initial-focus
      (click)="returnToInputFromPreflight()"
    >
      Return to input
    </button>
    @if (!preflightHasBlockingIssues()) {
      <button
        class="btn btn-primary"
        type="button"
        [disabled]="preflightContinuationInFlight()"
        (click)="continueAfterPreflight()"
      >
        {{ preflightContinuationInFlight() ? 'Starting...' : 'Continue with limitations' }}
      </button>
    }
  </div>
</app-modal-shell>

// DILIGENT/client/src/pages/DiliAgentPage.tsx
import React, { useCallback, useEffect, useRef, useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

import { BooleanToggle } from "../components/BooleanToggle";
import {
    DEFAULT_FORM_STATE,
    REPORT_EXPORT_FILENAME,
} from "../constants";
import { useAppState } from "../context/AppStateContext";
import { useObjectUrlLifecycle } from "../hooks/useObjectUrlLifecycle";
import {
    cancelClinicalJob,
    pollClinicalJobStatus,
    startClinicalJob,
} from "../services/api";
import { JobStatus, JobStatusResponse } from "../types";
import {
    buildClinicalPayload,
    createDownloadUrl,
    normalizeVisitDateInput,
} from "../utils";

const todayIso = new Date().toISOString().slice(0, 10);
const DEFAULT_POLL_INTERVAL_MS = 1000;

// ---------------------------------------------------------------------------
// Icons
// ---------------------------------------------------------------------------
const CopyIcon = () => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
        <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
    </svg>
);

const ExpandIcon = () => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <polyline points="15 3 21 3 21 9" />
        <polyline points="9 21 3 21 3 15" />
        <line x1="21" y1="3" x2="14" y2="10" />
        <line x1="3" y1="21" x2="10" y2="14" />
    </svg>
);

const DownloadIcon = () => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
        <polyline points="7 10 12 15 17 10" />
        <line x1="12" y1="15" x2="12" y2="3" />
    </svg>
);

const ClinicalInputIcon = ({ kind }: { kind: "anamnesis" | "drugs" | "labs" }) => {
    if (kind === "anamnesis") {
        return (
            <svg viewBox="0 0 24 24" aria-hidden="true">
                <path d="M6 4h9l3 3v13H6z" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
                <path d="M15 4v3h3" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
                <path d="M9 12h6M9 16h6" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" />
            </svg>
        );
    }
    if (kind === "drugs") {
        return (
            <svg viewBox="0 0 24 24" aria-hidden="true">
                <rect x="4" y="8" width="16" height="8" rx="4" fill="none" stroke="currentColor" strokeWidth="1.8" />
                <path d="M12 8v8" fill="none" stroke="currentColor" strokeWidth="1.8" />
            </svg>
        );
    }
    return (
        <svg viewBox="0 0 24 24" aria-hidden="true">
            <path d="M6 4h8l4 4v12H6z" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
            <path d="M14 4v4h4M9 13h6M9 17h4" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
        </svg>
    );
};

function isTerminalJobStatus(status: JobStatus | null): boolean {
    return status === "completed" || status === "failed" || status === "cancelled";
}

// ---------------------------------------------------------------------------
// DiliAgentPage
// ---------------------------------------------------------------------------
export function DiliAgentPage(): React.JSX.Element {
    const { state, updateDiliAgent } = useAppState();
    const {
        settings,
        form,
        message,
        exportUrl,
        jobId,
        jobProgress,
        jobStatus,
        jobStageMessage,
        isRunning,
        isExpanded,
    } = state.diliAgent;

    const pollerRef = useRef<{ stop: () => void } | null>(null);
    const [isCancelling, setIsCancelling] = useState(false);
    const { revokeObjectUrl } = useObjectUrlLifecycle(exportUrl);

    // Cleanup poller on unmount
    useEffect(() => {
        return () => {
            if (pollerRef.current) {
                pollerRef.current.stop();
                pollerRef.current = null;
            }
        };
    }, []);

    // ---------------------------------------------------------------------------
    // Handlers
    // ---------------------------------------------------------------------------
    const resetOutputs = () => {
        revokeObjectUrl(exportUrl);
        updateDiliAgent({
            message: "",
            exportUrl: null,
            jobId: null,
            jobProgress: 0,
            jobStatus: null,
            jobStage: null,
            jobStageMessage: null,
        });
    };

    const handleFormChange = <K extends keyof typeof form>(key: K, value: (typeof form)[K]) => {
        updateDiliAgent({ form: { ...form, [key]: value } });
    };

    const handleVisitDateChange = (value: string) => {
        handleFormChange("visitDate", normalizeVisitDateInput(value));
    };

    const stopPoller = useCallback(() => {
        if (pollerRef.current) {
            pollerRef.current.stop();
            pollerRef.current = null;
        }
    }, []);

    const handlePollingError = useCallback(
        (pollError: string) => {
            stopPoller();
            setIsCancelling(false);
            updateDiliAgent({
                message: `[ERROR] ${pollError}`,
                exportUrl: null,
                jobStage: null,
                jobStageMessage: null,
                isRunning: false,
            });
        },
        [stopPoller, updateDiliAgent],
    );

    const handleJobStatusUpdate = useCallback(
        (status: JobStatusResponse) => {
            const terminalStatus = isTerminalJobStatus(status.status);
            const stage =
                status.result && typeof status.result.progress_stage === "string"
                    ? status.result.progress_stage
                    : null;
            const stageMessage =
                status.result && typeof status.result.progress_message === "string"
                    ? status.result.progress_message
                    : null;
            const resolvedProgress =
                typeof status.progress === "number" ? status.progress : 0;
            updateDiliAgent({
                jobProgress: terminalStatus ? 100 : resolvedProgress,
                jobStatus: status.status,
                jobStage: stage,
                jobStageMessage: stageMessage,
                isRunning: !terminalStatus,
            });

            if (!terminalStatus) {
                return;
            }

            stopPoller();
            setIsCancelling(false);

            if (status.status === "completed") {
                const report =
                    typeof status.result?.report === "string"
                        ? status.result.report
                        : "";
                const newExportUrl = report
                    ? createDownloadUrl(report, REPORT_EXPORT_FILENAME)
                    : null;
                updateDiliAgent({
                    message: report || "[INFO] Clinical analysis completed.",
                    exportUrl: newExportUrl,
                    jobStage: null,
                    jobStageMessage: null,
                });
            } else if (status.status === "failed") {
                const errorMessage = status.error
                    ? `[ERROR] ${status.error}`
                    : "[ERROR] Clinical analysis failed.";
                updateDiliAgent({
                    message: errorMessage,
                    exportUrl: null,
                    jobStage: null,
                    jobStageMessage: null,
                });
            } else if (status.status === "cancelled") {
                updateDiliAgent({
                    message: "[INFO] Clinical analysis cancelled.",
                    exportUrl: null,
                    jobStage: null,
                    jobStageMessage: null,
                });
            }
        },
        [stopPoller, updateDiliAgent],
    );

    const startPolling = useCallback(
        (jobIdToPoll: string, intervalMs: number) => {
            stopPoller();
            pollerRef.current = pollClinicalJobStatus(
                jobIdToPoll,
                intervalMs,
                handleJobStatusUpdate,
                handlePollingError,
            );
        },
        [handleJobStatusUpdate, handlePollingError, stopPoller],
    );

    const executeRunSession = async () => {
        setIsCancelling(false);
        updateDiliAgent({ isRunning: true });
        resetOutputs();
        stopPoller();
        try {
            const payload = buildClinicalPayload(form, settings);
            const startResult = await startClinicalJob(payload);
            updateDiliAgent({
                jobId: startResult.job_id,
                jobProgress: 0,
                jobStatus: startResult.status,
                jobStage: "session_initialization",
                jobStageMessage: "Initializing clinical session",
            });
            const intervalMs = startResult.poll_interval * 1000;
            startPolling(startResult.job_id, intervalMs);
        } catch (error) {
            const description =
                error instanceof Error ? error.message : "Unexpected error";
            updateDiliAgent({
                message: `[ERROR] ${description}`,
                exportUrl: null,
                jobStage: null,
                jobStageMessage: null,
                isRunning: false,
            });
        } finally {
            if (!pollerRef.current) {
                updateDiliAgent({ isRunning: false });
            }
        }
    };

    useEffect(() => {
        if (!isRunning || !jobId || isTerminalJobStatus(jobStatus) || pollerRef.current) {
            return;
        }
        startPolling(jobId, DEFAULT_POLL_INTERVAL_MS);
    }, [isRunning, jobId, jobStatus, startPolling]);

    const handleRunSession = async () => {
        const missingMessageByField: Array<[keyof typeof form, string]> = [
            ["anamnesis", "[ERROR] Provide the anamnesis."],
            ["visitDate", "[ERROR] Provide the visit date."],
            ["drugs", "[ERROR] Provide current drugs."],
            [
                "laboratoryAnalysis",
                "[ERROR] Provide laboratory data sufficient to determine hepatotoxicity pattern, ideally dated ALT or AST, ALP, and bilirubin.",
            ],
        ];
        const firstMissing = missingMessageByField.find(
            ([field]) => !String(form[field]).trim(),
        );
        if (firstMissing) {
            resetOutputs();
            updateDiliAgent({
                isRunning: false,
                message: firstMissing[1],
                exportUrl: null,
                jobStage: null,
                jobStageMessage: null,
            });
            return;
        }
        await executeRunSession();
    };

    const handleStopSession = async () => {
        if (!jobId) {
            return;
        }
        setIsCancelling(true);
        try {
            await cancelClinicalJob(jobId);
            updateDiliAgent({
                message: "[INFO] Cancellation requested. Waiting for worker shutdown...",
            });
        } catch (error) {
            const description =
                error instanceof Error ? error.message : "Failed to request cancellation.";
            updateDiliAgent({
                message: `[ERROR] ${description}`,
            });
        } finally {
            setIsCancelling(false);
        }
    };

    const handleClear = () => {
        revokeObjectUrl(exportUrl);
        updateDiliAgent({
            form: { ...DEFAULT_FORM_STATE },
            message: "",
            exportUrl: null,
            jobId: null,
            jobProgress: 0,
            jobStatus: null,
            jobStage: null,
            jobStageMessage: null,
        });
    };

    const handleDownload = () => {
        if (!exportUrl) return;
        const anchor = document.createElement("a");
        anchor.href = exportUrl;
        anchor.download = REPORT_EXPORT_FILENAME;
        anchor.click();
    };

    const handleCopyReport = async () => {
        if (message) {
            try {
                await navigator.clipboard.writeText(message);
            } catch (err) {
                console.error("Failed to copy:", err);
            }
        }
    };

    const handleToggleExpand = () => {
        updateDiliAgent({ isExpanded: !isExpanded });
    };

    const recordedDateLabel = form.visitDate
        ? new Date(`${form.visitDate}T00:00:00`).toLocaleDateString(undefined, {
            year: "numeric",
            month: "long",
            day: "numeric",
        })
        : "Not set";
    const patientNameLabel = form.patientName.trim() || "Unnamed patient";

    // ---------------------------------------------------------------------------
    // Render
    // ---------------------------------------------------------------------------
    const spinner = (
        <div className="session-spinner" role="status" aria-live="polite">
            <div className="spinner-wheel" />
            <p className="spinner-label">
                {`${jobStageMessage || "Generating report"}${
                    jobProgress > 0 ? `... ${Math.round(jobProgress)}%` : "..."
                }`}
            </p>
        </div>
    );

    const reportContent = (() => {
        if (isRunning && !isTerminalJobStatus(jobStatus)) {
            return spinner;
        }
        if (message) {
            return (
                <ReactMarkdown remarkPlugins={[remarkGfm]} className="markdown">
                    {message}
                </ReactMarkdown>
            );
        }
        return (
            <div className="report-placeholder">
                No report generated yet. Run analysis to see results.
            </div>
        );
    })();
    return (
        <main className="page-container stitch-dili-page">
            <div className="stitch-dili-grid">
                <div className="stitch-dili-main">
                    <section className="stitch-dili-card">
                        <div className="stitch-dili-input-stack">
                            <div className="stitch-dili-input-group">
                                <h3><ClinicalInputIcon kind="anamnesis" /><span>Anamnesis</span></h3>
                                <textarea
                                    id="anamnesis"
                                    placeholder="Describe patient history, symptoms onset, and clinical observations..."
                                    value={form.anamnesis}
                                    onChange={(e) => handleFormChange("anamnesis", e.target.value)}
                                />
                            </div>

                            <div className="stitch-dili-input-group">
                                <h3><ClinicalInputIcon kind="drugs" /><span>Current Drugs</span></h3>
                                <textarea
                                    id="drugs"
                                    placeholder="List medications, dosages, frequency, and duration of use..."
                                    value={form.drugs}
                                    onChange={(e) => handleFormChange("drugs", e.target.value)}
                                />
                            </div>

                            <div className="stitch-dili-input-group">
                                <h3><ClinicalInputIcon kind="labs" /><span>Laboratory Analysis</span></h3>
                                <textarea
                                    id="laboratory-analysis"
                                    placeholder="Input raw lab results (ALT, AST, ALP, Bilirubin, etc.)..."
                                    value={form.laboratoryAnalysis}
                                    onChange={(e) => handleFormChange("laboratoryAnalysis", e.target.value)}
                                />
                            </div>
                        </div>
                    </section>
                </div>

                <aside className="stitch-dili-sidebar">
                    <section className="stitch-dili-card stitch-dili-patient">
                        <div className="stitch-dili-patient-top">
                            <div className="stitch-dili-avatar" aria-hidden="true">
                                {patientNameLabel.charAt(0).toUpperCase()}
                            </div>
                            <div>
                                <h3>{patientNameLabel}</h3>
                                <p>Recorded: {recordedDateLabel}</p>
                            </div>
                        </div>

                        <div className="stitch-dili-inline-fields">
                            <div className="field">
                                <label className="field-label" htmlFor="patient-name">Patient Name</label>
                                <input
                                    id="patient-name"
                                    type="text"
                                    placeholder="e.g., Marco Rossi"
                                    value={form.patientName}
                                    onChange={(e) => handleFormChange("patientName", e.target.value)}
                                />
                            </div>
                            <div className="field">
                                <label className="field-label" htmlFor="visit-date">Visit Date</label>
                                <input
                                    id="visit-date"
                                    type="date"
                                    max={todayIso}
                                    value={form.visitDate}
                                    onChange={(e) => handleVisitDateChange(e.target.value)}
                                />
                            </div>
                        </div>

                        <div className="stitch-dili-controls">
                            <p>Retrieval Controls</p>
                            <BooleanToggle
                                id="use-rag"
                                label="Internal RAG"
                                checked={form.useRag}
                                onChange={(checked) => handleFormChange("useRag", checked)}
                            />
                            <BooleanToggle
                                id="use-web-search"
                                label="Web Search"
                                checked={form.useWebSearch}
                                onChange={(checked) => handleFormChange("useWebSearch", checked)}
                            />
                        </div>

                        <div className="stitch-dili-actions">
                            <button
                                className="btn btn-primary"
                                type="button"
                                disabled={isCancelling}
                                onClick={() => { void (isRunning ? handleStopSession() : handleRunSession()); }}
                            >
                                {isRunning ? (isCancelling ? "Stopping..." : "Stop analysis") : "Run DILI analysis"}
                            </button>
                            <button className="stitch-dili-clear" type="button" onClick={handleClear} disabled={isRunning}>
                                Clear all
                            </button>
                        </div>
                    </section>

                    <div className="stitch-dili-tip">
                        "Ensure laboratory results include units for accurate drug-induced liver injury risk profiling."
                    </div>
                </aside>
            </div>

            <section className="report-section stitch-dili-report">
                <div className="report-shell">
                    <div className="report-header">
                        <p className="report-eyebrow">Report Output</p>
                    </div>

                    <div className="report-toolbar">
                        <button
                            className="toolbar-btn"
                            type="button"
                            onClick={handleCopyReport}
                            disabled={!message}
                            title="Copy to clipboard"
                        >
                            <CopyIcon />
                            <span>Copy</span>
                        </button>
                        <button
                            className="toolbar-btn"
                            type="button"
                            onClick={handleToggleExpand}
                            disabled={!message}
                            title={isExpanded ? "Collapse" : "Expand"}
                        >
                            <ExpandIcon />
                            <span>{isExpanded ? "Collapse" : "Expand"}</span>
                        </button>
                        <button
                            className="toolbar-btn"
                            type="button"
                            onClick={handleDownload}
                            disabled={!exportUrl}
                            title="Download markdown file"
                        >
                            <DownloadIcon />
                            <span>Download markdown</span>
                        </button>
                    </div>

                    <div className={`report-content ${isExpanded ? "is-expanded" : ""}`}>
                        {reportContent}
                    </div>
                </div>
            </section>
        </main>
    );
}
