// app/client/src/app/pages/model-config/model-config-page.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnInit, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';

import { ProviderAccessCardComponent } from '../../components/provider-access-card/provider-access-card.component';
import {
  StatusMessageComponent,
  resolveStatusTone,
} from '../../components/status-message/status-message.component';
import { AppStateService } from '../../core/state/app-state.service';
import { formatUnknownError } from '../../core/utils';
import { CLOUD_MODEL_CHOICES } from '../../core/constants';
import {
  buildRuntimeSettingsFromConfig,
  resolveCloudChoices,
  resolveCloudModel,
  resolveProvider,
} from '../../core/model-config';
import {
  AccessKeyProvider,
  CloudProvider,
  JobStatus,
  ModelConfigStateResponse,
  ModelConfigUpdateRequest,
  RuntimeSettings,
} from '../../core/models/types';
import {
  fetchModelConfigState,
  fetchModelPullJobStatus,
  startModelPullJob,
  updateModelConfigState,
} from '../../core/services/model-config-api';
import { JobPollingService } from '../../core/services/job-polling.service';
import { AccessKeyModalComponent } from './components/access-key-modal.component';
import { ModelRoleActionButtonComponent } from './components/model-role-action-button.component';
import {
  MODEL_FILTERS,
  modelMatchesFilters,
  resolveDraftFromSettings,
} from './model-catalog';
import {
  DraftRuntimeConfig,
  ModelFilterKey,
  ModelPullProgressState,
  ModelRole,
} from './model-config.types';

const DEFAULT_CLOUD_PROVIDERS: readonly CloudProvider[] = ['openai', 'gemini'];

const PROVIDER_LABELS: Record<AccessKeyProvider, string> = {
  openai: 'OpenAI',
  gemini: 'Gemini',
  brave: 'Brave Search',
};

const TERMINAL_JOB_STATUSES: readonly JobStatus[] = ['completed', 'failed', 'cancelled'];

function isCloudProvider(provider: string): provider is CloudProvider {
  return provider === 'openai' || provider === 'gemini';
}

function resolveProviderLabel(provider: string): string {
  if (provider === 'openai' || provider === 'gemini' || provider === 'brave') {
    return PROVIDER_LABELS[provider];
  }
  return provider;
}

@Component({
  selector: 'app-model-config-page',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ProviderAccessCardComponent,
    StatusMessageComponent,
    AccessKeyModalComponent,
    ModelRoleActionButtonComponent,
  ],
  templateUrl: './model-config-page.component.html',
  styleUrl: './model-config-page.component.scss',
})
export class ModelConfigPageComponent implements OnInit {
  readonly appState = inject(AppStateService);
  private readonly jobPolling = inject(JobPollingService);

  readonly modelFilters = MODEL_FILTERS;

  readonly isLoading = signal(true);
  readonly hasLoadedConfig = signal(false);
  readonly isSaving = signal(false);
  readonly localModels = signal<ModelConfigStateResponse['local_models']>([]);
  readonly cloudChoices = signal(CLOUD_MODEL_CHOICES);
  readonly modelSearchQuery = signal('');
  readonly statusMessage = signal('');
  readonly openProviderModal = signal<AccessKeyProvider | null>(null);
  readonly modelPullProgress = signal<Record<string, ModelPullProgressState>>({});
  readonly activeFilters = signal<Record<ModelFilterKey, boolean>>({
    installed: false,
    reasoning: false,
    small: false,
    extraction: false,
  });
  readonly draftConfig = signal<DraftRuntimeConfig>(resolveDraftFromSettings(this.appState.state().diliAgent.settings));

  readonly filteredLocalModels = computed(() => {
    const query = this.modelSearchQuery().trim().toLowerCase();
    return this.localModels().filter((model) =>
      modelMatchesFilters(model, query, this.activeFilters()),
    );
  });

  readonly availableLocalModelCount = computed(
    () => this.localModels().filter((model) => model.available_in_ollama).length,
  );

  readonly draftProvider = computed(() =>
    resolveProvider(this.draftConfig().provider, this.cloudChoices()),
  );

  readonly draftCloudModel = computed(() =>
    resolveCloudModel(this.draftProvider(), this.draftConfig().cloudModel, this.cloudChoices()),
  );

  readonly activeCloudModels = computed(() => this.cloudChoices()[this.draftProvider()] || []);

  readonly runtimeLabel = computed(() =>
    this.draftConfig().useCloudServices
      ? `Cloud (${resolveProviderLabel(this.draftProvider())})`
      : 'Local (Ollama)',
  );

  readonly statusTone = computed(() => resolveStatusTone(this.statusMessage()));

  readonly cloudProviderOptions = computed<CloudProvider[]>(() => {
    const values = Object.keys(this.cloudChoices());
    const providers = values.filter(isCloudProvider);
    if (providers.length) {
      return providers;
    }
    return [...DEFAULT_CLOUD_PROVIDERS];
  });

  readonly missingRequiredModels = computed(() => {
    const draft = this.draftConfig();
    if (draft.useCloudServices) return [];
    const modelMap = new Map(this.localModels().map((model) => [model.name, model]));
    const missing = new Set<string>();
    for (const modelName of [draft.clinicalModel, draft.textExtractionModel]) {
      const candidate = modelName.trim();
      if (!candidate) continue;
      const localModel = modelMap.get(candidate);
      if (!localModel || !localModel.available_in_ollama) missing.add(candidate);
    }
    return Array.from(missing);
  });

  readonly noLocalModelMessage = computed(() => {
    if (this.isLoading()) return 'Loading local model catalog...';
    if (!this.localModels().length) return 'No local model catalog entries available.';
    if (!this.filteredLocalModels().length) {
      const q = this.modelSearchQuery().trim();
      return q ? `No models match "${q}".` : 'No models match the active filters.';
    }
    return '';
  });

  readonly saveDisabled = computed(() => {
    const settings = this.appState.state().diliAgent.settings;
    const draft = this.draftConfig();
    const savedProvider = resolveProvider(settings.provider, this.cloudChoices());
    const savedCloudModel = resolveCloudModel(savedProvider, settings.cloudModel, this.cloudChoices());
    const hasPendingChanges =
      draft.useCloudServices !== settings.useCloudServices ||
      this.draftProvider() !== savedProvider ||
      (this.draftCloudModel() || '') !== (savedCloudModel || '') ||
      draft.clinicalModel !== settings.clinicalModel ||
      draft.textExtractionModel !== settings.textExtractionModel ||
      draft.temperature !== settings.temperature;

    return (
      this.isLoading() ||
      this.isSaving() ||
      !hasPendingChanges ||
      (draft.useCloudServices && !this.draftCloudModel())
    );
  });

  async ngOnInit(): Promise<void> {
    await this.loadModelConfig(true, true);
  }

  async loadModelConfig(syncDraft = true, includeLocalAvailability: boolean = true): Promise<void> {
    this.isLoading.set(true);
    try {
      const payload = await fetchModelConfigState(includeLocalAvailability);
      this.applyConfigToState(payload, syncDraft);
      this.statusMessage.set('');
    } catch (error) {
      this.statusMessage.set(formatUnknownError(error, 'Unable to load model settings.'));
    } finally {
      this.isLoading.set(false);
      this.hasLoadedConfig.set(true);
    }
  }

  private applyConfigToState(payload: ModelConfigStateResponse, syncDraft: boolean): void {
    this.localModels.set(payload.local_models || []);
    const choices = resolveCloudChoices(payload.cloud_model_choices);
    this.cloudChoices.set(choices);

    const current = this.appState.state().diliAgent.settings;
    const nextSettings: RuntimeSettings = buildRuntimeSettingsFromConfig(payload, current);
    this.appState.updateDiliAgent({ settings: nextSettings });

    if (syncDraft) {
      this.draftConfig.set(resolveDraftFromSettings(nextSettings));
    }
  }

  async persistConfigPatch(patch: ModelConfigUpdateRequest, successMessage = '', syncDraft = true): Promise<void> {
    this.isSaving.set(true);
    try {
      const payload = await updateModelConfigState(patch);
      this.applyConfigToState(payload, syncDraft);
      this.statusMessage.set(successMessage);
    } catch (error) {
      this.statusMessage.set(formatUnknownError(error, 'Unable to save model settings.'));
    } finally {
      this.isSaving.set(false);
    }
  }

  toggleFilter(key: ModelFilterKey): void {
    this.activeFilters.update((current) => ({ ...current, [key]: !current[key] }));
  }

  setModelSearchQuery(value: string): void {
    this.modelSearchQuery.set(value);
  }

  handleRoleSelection(role: ModelRole, modelName: string): void {
    this.draftConfig.update((previous) => ({
      ...previous,
      clinicalModel: role === 'clinical' ? modelName : previous.clinicalModel,
      textExtractionModel: role === 'text_extraction' ? modelName : previous.textExtractionModel,
    }));
  }

  handleCloudSwitchChange(value: boolean): void {
    this.draftConfig.update((previous) => ({ ...previous, useCloudServices: value }));
    if (!value) {
      void this.loadModelConfig(false, true);
    }
  }

  handleProviderChange(provider: CloudProvider): void {
    const resolvedProvider = resolveProvider(provider, this.cloudChoices());
    const cloudModel = resolveCloudModel(resolvedProvider, null, this.cloudChoices());
    this.draftConfig.update((previous) => ({
      ...previous,
      provider: resolvedProvider,
      cloudModel,
    }));
  }

  handleCloudModelChange(modelName: string): void {
    this.draftConfig.update((previous) => ({ ...previous, cloudModel: modelName || null }));
  }

  async handleReasoningChange(enabled: boolean): Promise<void> {
    await this.persistConfigPatch({ ollama_reasoning: enabled }, 'Extra parameters saved.', false);
  }

  setTemperature(value: string): void {
    const parsed = Number.parseFloat(value);
    if (!Number.isFinite(parsed)) return;
    const bounded = Math.max(0, Math.min(2, parsed));
    this.draftConfig.update((previous) => ({
      ...previous,
      temperature: bounded,
    }));
  }

  async handleSaveConfiguration(): Promise<void> {
    const draft = this.draftConfig();
    const patch: ModelConfigUpdateRequest = {
      use_cloud_services: draft.useCloudServices,
      llm_provider: this.draftProvider(),
      cloud_model: this.draftCloudModel(),
      ollama_temperature: draft.temperature,
      cloud_temperature: draft.temperature,
    };
    if (!draft.useCloudServices) {
      patch.clinical_model = draft.clinicalModel || null;
      patch.text_extraction_model = draft.textExtractionModel || null;
    }
    await this.persistConfigPatch(
      patch,
      'Configuration saved.',
      true,
    );
  }

  openKeys(provider: AccessKeyProvider): void {
    this.openProviderModal.set(provider);
  }

  closeKeys(): void {
    this.openProviderModal.set(null);
  }

  async pullModelByName(modelName: string): Promise<void> {
    const candidate = modelName.trim();
    if (!candidate) {
      this.statusMessage.set('[ERROR] Enter a model name to pull from Ollama.');
      return;
    }
    await this.runPull([candidate], `[INFO] Pulling '${candidate}' from Ollama...`);
  }

  async installRequiredModels(modelNames: readonly string[]): Promise<void> {
    if (!modelNames.length) return;
    await this.runPull(modelNames, `[INFO] Installing required models: ${modelNames.join(', ')}.`);
  }

  private async runPull(models: readonly string[], startMessage: string): Promise<void> {
    const requested = Array.from(new Set(models.map((m) => m.trim()).filter((m) => !!m)));
    if (!requested.length) return;

    this.appState.updateDiliAgent({ isPulling: true });
    this.statusMessage.set(startMessage);
    let failureMessage = '';
    const completed: string[] = [];

    try {
      for (const modelName of requested) {
        this.updateModelPullProgress(modelName, {
          progress: 1,
          status: 'pending',
          message: `Starting pull for '${modelName}'...`,
        });

        try {
          const start = await startModelPullJob(modelName);
          const intervalMs = Math.max(250, Math.round(start.poll_interval * 1000));
          await this.pollPullJob(modelName, start.job_id, intervalMs);
          completed.push(modelName);
        } catch (error) {
          const description = error instanceof Error ? error.message : `Failed to pull '${modelName}'.`;
          failureMessage = description.startsWith('[ERROR]') ? description : `[ERROR] ${description}`;
          break;
        } finally {
          this.updateModelPullProgress(modelName, null);
        }
      }

      if (!failureMessage) {
        this.statusMessage.set(
          completed.length === 1
            ? `[INFO] Model available locally: ${completed[0]}.`
            : `[INFO] Models available locally: ${completed.join(', ')}.`,
        );
      }
    } finally {
      await this.loadModelConfig(false, true);
      if (failureMessage) {
        this.statusMessage.set(failureMessage);
      }
      this.appState.updateDiliAgent({ isPulling: false });
    }
  }

  private async pollPullJob(modelName: string, jobId: string, intervalMs: number): Promise<void> {
    const safeIntervalMs = Math.max(250, intervalMs);
    const requestTimeoutSeconds = Math.min(30, Math.max(5, Math.ceil((safeIntervalMs / 1000) * 4)));

    await this.jobPolling.run({
      intervalMs: safeIntervalMs,
      pollStep: async () => {
        const payload = await fetchModelPullJobStatus(jobId, requestTimeoutSeconds);
        const progress = Math.max(0, Math.min(100, payload.progress));
        const message =
          typeof payload.result?.progress_message === 'string' && payload.result.progress_message.trim()
            ? payload.result.progress_message
            : payload.status === 'completed'
              ? `Model '${modelName}' is available locally.`
              : payload.status === 'cancelled'
                ? `Pull cancelled for '${modelName}'.`
                : payload.status === 'failed'
                  ? `Pull failed for '${modelName}'.`
                  : `Pulling '${modelName}' from Ollama...`;

        this.updateModelPullProgress(modelName, {
          progress,
          status: payload.status,
          message,
        });

        if (!TERMINAL_JOB_STATUSES.includes(payload.status)) {
          return true;
        }
        if (payload.status === 'completed') {
          return false;
        }
        const errorMessage = payload.error?.trim() || message;
        throw new Error(`[ERROR] ${errorMessage}`);
      },
    });
  }

  private updateModelPullProgress(modelName: string, progress: ModelPullProgressState | null): void {
    this.modelPullProgress.update((current) => {
      if (progress === null) {
        if (!(modelName in current)) return current;
        const { [modelName]: removed, ...rest } = current;
        void removed;
        return rest;
      }
      return { ...current, [modelName]: progress };
    });
  }

  getProviderLabel(provider: AccessKeyProvider): string {
    return PROVIDER_LABELS[provider];
  }

  resolveProviderLabel(provider: string): string {
    return resolveProviderLabel(provider);
  }

  progressForModel(name: string): ModelPullProgressState | null {
    return this.modelPullProgress()[name] || null;
  }

  isFilterActive(key: ModelFilterKey): boolean {
    return this.activeFilters()[key];
  }
}


<main class="page-container model-config-page">
  <header class="model-config-header-compact">
    <h1>Model Configurations</h1>
    <p class="lede">Adjust runtime preferences for DILI analysis.</p>
  </header>

  @if (!hasLoadedConfig()) {
    <section class="model-config-loading-state" role="status" aria-live="polite">
      Loading model configuration...
    </section>
  } @else {
  <div class="model-config-layout">
    <div class="model-config-main-column">
      <section class="model-config-runtime-row" aria-label="Runtime source selector">
        <h2 class="modal-section-title">Runtime Source</h2>
        <div class="model-config-runtime-options">
          <label class="model-config-runtime-option" [class.is-active]="!draftConfig().useCloudServices">
            <input
              type="radio"
              name="runtime-source"
              [checked]="!draftConfig().useCloudServices"
              (change)="handleCloudSwitchChange(false)"
              [disabled]="isSaving() || isLoading()"
            />
            <span>
              <span class="field-label">Local Models (Ollama)</span>
              <span class="field-helper">Run both model roles using local Ollama models.</span>
            </span>
          </label>
          <label class="model-config-runtime-option" [class.is-active]="draftConfig().useCloudServices">
            <input
              type="radio"
              name="runtime-source"
              [checked]="draftConfig().useCloudServices"
              (change)="handleCloudSwitchChange(true)"
              [disabled]="isSaving() || isLoading()"
            />
            <span>
              <span class="field-label">Cloud Models (OpenAI / Gemini)</span>
              <span class="field-helper">Use a cloud provider and configured cloud model.</span>
            </span>
          </label>
        </div>
      </section>

      @if (!draftConfig().useCloudServices) {
        <section class="model-config-local-row" [class.is-disabled]="isSaving() || isLoading()" [attr.aria-disabled]="isSaving() || isLoading()">
          <div class="model-config-row-header">
            <div class="model-config-row-header-top">
              <div class="model-config-row-heading">
                <h2 class="modal-section-title">Local Model Catalog</h2>
                <span class="model-config-caption">{{ availableLocalModelCount() }} installed in Ollama.</span>
              </div>
              <div class="model-config-search-and-filters">
                <div class="model-config-search">
                  <input
                    type="search"
                    placeholder="Search models"
                    [ngModel]="modelSearchQuery()"
                    (ngModelChange)="setModelSearchQuery($event)"
                  />
                </div>
                <div class="model-config-filter-pills">
                  @for (filter of modelFilters; track filter.key) {
                    <button
                      type="button"
                      class="model-config-filter-pill"
                      [class.is-active]="isFilterActive(filter.key)"
                      (click)="toggleFilter(filter.key)"
                    >
                      {{ filter.label }}
                    </button>
                  }
                </div>
              </div>
            </div>
          </div>

          <div class="model-config-list-shell">
            <ul class="model-config-model-list">
              @if (noLocalModelMessage()) {
                <li class="model-config-empty-note">{{ noLocalModelMessage() }}</li>
              }
              @for (model of filteredLocalModels(); track model.name) {
                <li class="model-config-model-item" [class.is-selected]="draftConfig().clinicalModel === model.name || draftConfig().textExtractionModel === model.name">
                  <div class="model-config-model-details">
                    <div class="model-config-model-name-row">
                      <span class="model-config-model-name">{{ model.name }}</span>
                      <span class="model-config-availability-pill" [class.is-available]="model.available_in_ollama" [class.is-unavailable]="!model.available_in_ollama">
                        {{ model.available_in_ollama ? 'Installed' : 'Not installed' }}
                      </span>
                    </div>
                    <span class="model-config-model-description" [title]="model.description">{{ model.description }}</span>

                    @if (progressForModel(model.name); as progress) {
                      <div class="model-config-pull-progress" role="status" aria-live="polite">
                        <div class="model-config-pull-progress-track" aria-hidden="true">
                          <div class="model-config-pull-progress-fill" [style.width.%]="progress.progress"></div>
                        </div>
                        <p class="model-config-pull-progress-label">{{ progress.message }}</p>
                      </div>
                    }

                    <div class="model-config-role-pill-row" aria-live="polite">
                      @if (draftConfig().clinicalModel === model.name) {
                        <span class="model-config-role-pill">Clinical</span>
                      }
                      @if (draftConfig().textExtractionModel === model.name) {
                        <span class="model-config-role-pill">Text extraction</span>
                      }
                    </div>
                  </div>

                  <div class="model-config-model-item-side">
                    <div class="model-config-model-action-row">
                      @if (!model.available_in_ollama) {
                        <button
                          class="btn btn-secondary model-config-inline-btn"
                          type="button"
                          (click)="pullModelByName(model.name)"
                          [disabled]="isSaving() || isLoading() || appState.state().diliAgent.isPulling"
                        >
                          {{ progressForModel(model.name) ? 'Installing...' : 'Install' }}
                        </button>
                      }

                      <app-model-role-action-button
                        role="clinical"
                        [modelName]="model.name"
                        [selected]="draftConfig().clinicalModel === model.name"
                        [disabled]="isSaving() || isLoading()"
                        (roleSelected)="handleRoleSelection($event, model.name)"
                      />
                      <app-model-role-action-button
                        role="text_extraction"
                        [modelName]="model.name"
                        [selected]="draftConfig().textExtractionModel === model.name"
                        [disabled]="isSaving() || isLoading()"
                        (roleSelected)="handleRoleSelection($event, model.name)"
                      />
                    </div>
                  </div>
                </li>
              }
            </ul>
          </div>
        </section>
      }

      @if (draftConfig().useCloudServices) {
        <section class="model-config-cloud-row">
          <h2 class="modal-section-title">Cloud Model Configuration</h2>
          <div class="model-config-cloud-layout">
            <div class="model-config-cloud-controls">
              <div class="model-config-provider-list model-config-provider-list-narrow">
                @for (provider of cloudProviderOptions(); track provider) {
                  <app-provider-access-card
                    variant="selectable"
                    [label]="getProviderLabel(provider)"
                    [isActive]="draftProvider() === provider"
                    [disabled]="isSaving() || isLoading()"
                    [manageKeyAriaLabel]="'Manage ' + getProviderLabel(provider) + ' access keys'"
                    (select)="handleProviderChange(provider)"
                    (manageKeys)="openKeys(provider)"
                  ></app-provider-access-card>
                }
              </div>

              <div class="field model-config-cloud-model-field model-config-cloud-model-field-narrow">
                <label class="field-label" for="cloud-model-select">Cloud Model</label>
                <select
                  id="cloud-model-select"
                  [ngModel]="draftCloudModel() || ''"
                  (ngModelChange)="handleCloudModelChange($event)"
                  [disabled]="isSaving() || isLoading() || !activeCloudModels().length"
                >
                  @for (modelName of activeCloudModels(); track modelName) {
                    <option [value]="modelName">{{ modelName }}</option>
                  }
                </select>
              </div>
            </div>

            <p class="model-config-cloud-description">Provider configuration appears only when cloud runtime is selected.</p>
          </div>
        </section>
      }

    </div>

    <aside class="model-config-summary-panel">
      <h2 class="modal-section-title">Current Configuration</h2>
      <dl class="model-config-summary-list">
        <div><dt>Runtime</dt><dd>{{ runtimeLabel() }}</dd></div>
        <div><dt>Clinical Model</dt><dd>{{ draftConfig().clinicalModel || 'Not set' }}</dd></div>
        <div><dt>Text Extraction</dt><dd>{{ draftConfig().textExtractionModel || 'Not set' }}</dd></div>
        @if (draftConfig().useCloudServices) {
          <div><dt>Cloud Model</dt><dd>{{ draftCloudModel() || 'Not set' }}</dd></div>
        }
        <div><dt>Temperature</dt><dd>{{ draftConfig().temperature.toFixed(2) }}</dd></div>
      </dl>

      @if (!draftConfig().useCloudServices) {
        <div class="model-config-missing">
          <h3 class="model-config-summary-subtitle">Missing dependencies</h3>
          @if (missingRequiredModels().length) {
            <ul class="model-config-missing-list">
              @for (modelName of missingRequiredModels(); track modelName) {
                <li>{{ modelName }} not installed</li>
              }
            </ul>
          } @else {
            <p class="model-config-caption">All selected local models are installed.</p>
          }
        </div>
      }

      <section class="model-config-extra-row model-config-extra-row--side" [class.is-disabled]="isSaving() || isLoading()" [attr.aria-disabled]="isSaving() || isLoading()">
        <h2 class="modal-section-title">Extra Parameters</h2>
        <div class="model-config-extra-columns">
          <div class="model-config-extra-left">
            <app-provider-access-card
              variant="compact"
              [label]="getProviderLabel('brave')"
              hint="Brave Search API key"
              [disabled]="isSaving() || isLoading()"
              manageKeyAriaLabel="Manage Brave Search access keys"
              (manageKeys)="openKeys('brave')"
            ></app-provider-access-card>
          </div>
          <div class="model-config-extra-right">
            <div class="field">
              <label class="field-label" for="global-temperature-input">Temperature</label>
              <input
                id="global-temperature-input"
                type="number"
                min="0"
                max="2"
                step="0.01"
                [ngModel]="draftConfig().temperature"
                (ngModelChange)="setTemperature($event)"
                [disabled]="isSaving() || isLoading()"
                class="model-config-temperature-input"
              />
            </div>
            <label class="field checkbox model-config-reasoning-field">
              <input
                type="checkbox"
                [ngModel]="appState.state().diliAgent.settings.reasoning"
                (ngModelChange)="handleReasoningChange($event)"
                [disabled]="isSaving() || isLoading()"
              />
              <span class="field-label">Enable SDL/Reasoning</span>
            </label>
          </div>
        </div>
      </section>

      <div class="model-config-summary-actions">
        @if (!draftConfig().useCloudServices && missingRequiredModels().length > 0) {
          <button
            class="btn btn-secondary"
            type="button"
            (click)="installRequiredModels(missingRequiredModels())"
            [disabled]="isLoading() || isSaving() || appState.state().diliAgent.isPulling"
          >
            {{ appState.state().diliAgent.isPulling ? 'Installing...' : 'Install Required Models' }}
          </button>
        }
        <button class="btn btn-primary" type="button" (click)="handleSaveConfiguration()" [disabled]="saveDisabled()">
          {{ isSaving() ? 'Saving...' : 'Save Configuration' }}
        </button>
      </div>
    </aside>
  </div>
  }

  <app-status-message [message]="statusMessage()" [tone]="statusTone()"></app-status-message>

  <app-access-key-modal
    [isOpen]="openProviderModal() !== null"
    [provider]="openProviderModal() || 'openai'"
    [providerLabel]="resolveProviderLabel(openProviderModal() || 'openai')"
    (closed)="closeKeys()"
  ></app-access-key-modal>
</main>

// DILIGENT/client/src/pages/ModelConfigPage.tsx
import React, { useEffect, useMemo, useState } from "react";

import { AccessKeyModal } from "../components/AccessKeyModal";
import { StatusMessage, resolveStatusTone } from "../components/StatusMessage";
import { CLOUD_MODEL_CHOICES } from "../constants";
import { useAppState } from "../context/AppStateContext";
import {
    CloudModelChoices,
    buildRuntimeSettingsFromConfig,
    resolveCloudChoices,
    resolveCloudModel,
    resolveProvider,
} from "../modelConfig";
import {
    fetchModelConfigState,
    pullModels,
    updateModelConfigState,
} from "../services/api";
import { AccessKeyProvider, ModelConfigStateResponse, ModelConfigUpdateRequest, RuntimeSettings } from "../types";

const PROVIDER_LABELS: Record<string, string> = {
    openai: "OpenAI",
    gemini: "Gemini",
    tavily: "Tavily",
};

const KeyIcon = () => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <circle cx="8" cy="15" r="3" />
        <path d="M11 15h10" />
        <path d="M18 12v6" />
    </svg>
);

const PullIcon = () => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
        <path d="M12 3v11" />
        <path d="m7 10 5 5 5-5" />
        <path d="M5 21h14" />
    </svg>
);

function isAccessKeyProvider(provider: string): provider is AccessKeyProvider {
    return provider === "openai" || provider === "gemini" || provider === "tavily";
}

function resolveAvailabilityBadgeClass(modelAvailableInOllama: boolean | undefined): string {
    return modelAvailableInOllama ? "model-config-summary-ok" : "model-config-summary-muted";
}

function resolveAvailabilityLabel(modelAvailableInOllama: boolean | undefined): string {
    if (modelAvailableInOllama === undefined) {
        return "Unknown";
    }
    return modelAvailableInOllama ? "Installed" : "Not installed";
}

export function ModelConfigPage(): React.JSX.Element {
    const { state, updateDiluAgent } = useAppState();
    const { settings, isPulling } = state.diluAgent;

    const [isLoading, setIsLoading] = useState(true);
    const [isSaving, setIsSaving] = useState(false);
    const [localModels, setLocalModels] = useState<ModelConfigStateResponse["local_models"]>([]);
    const [cloudChoices, setCloudChoices] = useState<CloudModelChoices>(CLOUD_MODEL_CHOICES);
    const [modelSearchQuery, setModelSearchQuery] = useState("");
    const [statusMessage, setStatusMessage] = useState("");
    const [openProviderModal, setOpenProviderModal] = useState<AccessKeyProvider | null>(null);

    const cloudEnabled = settings.useCloudServices;
    const localSelectionDisabled = cloudEnabled || isSaving || isLoading;
    const ollamaControlsDisabled = cloudEnabled || isSaving || isLoading;
    const availableLocalModelCount = useMemo(
        () => localModels.filter((model) => model.available_in_ollama).length,
        [localModels],
    );
    const filteredLocalModels = useMemo(() => {
        const query = modelSearchQuery.trim().toLowerCase();
        if (!query) {
            return localModels;
        }
        return localModels.filter((model) => model.name.toLowerCase().includes(query));
    }, [localModels, modelSearchQuery]);

    const applyConfigToState = (payload: ModelConfigStateResponse) => {
        setLocalModels(payload.local_models || []);
        const choices = resolveCloudChoices(payload.cloud_model_choices);
        setCloudChoices(choices);

        const nextSettings: RuntimeSettings = buildRuntimeSettingsFromConfig(payload, settings);
        updateDiluAgent({ settings: nextSettings });
    };

    const loadModelConfig = async () => {
        setIsLoading(true);
        try {
            const payload = await fetchModelConfigState();
            applyConfigToState(payload);
            setStatusMessage("");
        } catch (error) {
            const description = error instanceof Error ? error.message : "Unable to load model settings.";
            setStatusMessage(`[ERROR] ${description}`);
        } finally {
            setIsLoading(false);
        }
    };

    useEffect(() => {
        void loadModelConfig();
    }, []);

    const persistConfigPatch = async (patch: ModelConfigUpdateRequest) => {
        setIsSaving(true);
        try {
            const payload = await updateModelConfigState(patch);
            applyConfigToState(payload);
            setStatusMessage("");
        } catch (error) {
            const description = error instanceof Error ? error.message : "Unable to save model settings.";
            setStatusMessage(`[ERROR] ${description}`);
        } finally {
            setIsSaving(false);
        }
    };

    const providerOptions = useMemo(() => {
        const values = Object.keys(cloudChoices);
        if (values.length) {
            return values;
        }
        return ["openai", "gemini"];
    }, [cloudChoices]);

    const activeProvider = resolveProvider(settings.provider, cloudChoices);
    const activeCloudModel = resolveCloudModel(activeProvider, settings.cloudModel, cloudChoices);
    const activeCloudModels = cloudChoices[activeProvider] || [];
    const statusTone = resolveStatusTone(statusMessage);
    const selectedClinicalModel = useMemo(
        () => localModels.find((model) => model.name === settings.clinicalModel) || null,
        [localModels, settings.clinicalModel],
    );
    const selectedTextExtractionModel = useMemo(
        () => localModels.find((model) => model.name === settings.parsingModel) || null,
        [localModels, settings.parsingModel],
    );
    const clinicalAvailabilityClassName = resolveAvailabilityBadgeClass(
        selectedClinicalModel?.available_in_ollama,
    );
    const clinicalAvailabilityLabel = resolveAvailabilityLabel(
        selectedClinicalModel?.available_in_ollama,
    );
    const extractionAvailabilityClassName = resolveAvailabilityBadgeClass(
        selectedTextExtractionModel?.available_in_ollama,
    );
    const extractionAvailabilityLabel = resolveAvailabilityLabel(
        selectedTextExtractionModel?.available_in_ollama,
    );

    const handleRoleSelection = async (role: "clinical" | "text_extraction", modelName: string) => {
        if (role === "clinical") {
            await persistConfigPatch({ clinical_model: modelName });
            return;
        }
        await persistConfigPatch({ text_extraction_model: modelName });
    };

    const handleCloudSwitchChange = async (value: boolean) => {
        await persistConfigPatch({ use_cloud_services: value });
    };

    const handleProviderChange = async (provider: string) => {
        await persistConfigPatch({ llm_provider: provider });
    };

    const handleCloudModelChange = async (modelName: string) => {
        await persistConfigPatch({ cloud_model: modelName });
    };

    const handleReasoningChange = async (enabled: boolean) => {
        await persistConfigPatch({ ollama_reasoning: enabled });
    };

    const handlePullModel = async (requestedModelName: string) => {
        const candidate = requestedModelName.trim();
        if (!candidate) {
            setStatusMessage("[ERROR] Enter a model name to pull from Ollama.");
            return;
        }

        updateDiluAgent({ isPulling: true });
        setStatusMessage(`[INFO] Pulling '${candidate}' from Ollama...`);
        try {
            const result = await pullModels([candidate]);
            setStatusMessage(result.message);
            await loadModelConfig();
        } finally {
            updateDiluAgent({ isPulling: false });
        }
    };

    return (
        <main className="page-container model-config-page">
            <header className="page-header">
                <p className="eyebrow">DILIGENT Clinical Copilot</p>
                <h1>Model Configurations</h1>
                <p className="lede">Adjust runtime preferences for DILI analysis.</p>
            </header>

            <div className="model-config-layout">
                <section className="model-config-left-column">
                    <div className={`model-config-local-row ${localSelectionDisabled ? "is-disabled" : ""}`} aria-disabled={localSelectionDisabled}>
                        <div className="model-config-row-header">
                            <div className="model-config-row-header-top">
                                <div>
                                    <h2 className="modal-section-title">Local Model Catalog</h2>
                                    <p className="helper">
                                        Select one clinical model and one text extraction model from the full catalog.
                                        {` ${availableLocalModelCount} installed in Ollama.`}
                                    </p>
                                </div>
                                <div className="model-config-search">
                                    <label className="visually-hidden" htmlFor="model-search-by-name">Search model by name</label>
                                    <input
                                        id="model-search-by-name"
                                        type="text"
                                        value={modelSearchQuery}
                                        placeholder="Search by name..."
                                        onChange={(event) => setModelSearchQuery(event.target.value)}
                                        disabled={isLoading}
                                    />
                                </div>
                            </div>
                        </div>

                        <ul className="model-config-local-cards">
                            {!localModels.length && (
                                <li className="model-config-empty-note">
                                    {isLoading ? "Loading local model catalog..." : "No local model catalog entries available."}
                                </li>
                            )}

                            {!!localModels.length && !filteredLocalModels.length && (
                                <li className="model-config-empty-note">
                                    No models match "{modelSearchQuery.trim()}".
                                </li>
                            )}

                            {filteredLocalModels.map((model) => (
                                <li
                                    key={model.name}
                                    className={`model-config-local-card ${model.available_in_ollama ? "is-available" : ""}`}
                                >
                                    <div className="model-config-local-card-header">
                                        <h3>{model.name}</h3>
                                        <div className="model-config-local-card-actions">
                                            <span
                                                className={`model-config-availability-pill ${model.available_in_ollama ? "is-available" : "is-unavailable"}`}
                                            >
                                                {model.available_in_ollama ? "Available in Ollama" : "Not installed"}
                                            </span>
                                            {!model.available_in_ollama && (
                                                <button
                                                    className="model-config-card-pull"
                                                    type="button"
                                                    onClick={() => { void handlePullModel(model.name); }}
                                                    disabled={isPulling || ollamaControlsDisabled}
                                                    aria-label={`Pull ${model.name} from Ollama`}
                                                    title={`Pull ${model.name}`}
                                                >
                                                    <PullIcon />
                                                </button>
                                            )}
                                        </div>
                                    </div>
                                    <p className="model-config-family">Family: {model.family}</p>
                                    <p>{model.description}</p>
                                    <div className="model-config-role-controls">
                                        <label className="field checkbox">
                                            <input
                                                type="radio"
                                                name="clinical-role"
                                                checked={settings.clinicalModel === model.name}
                                                onChange={() => { void handleRoleSelection("clinical", model.name); }}
                                                disabled={localSelectionDisabled}
                                            />
                                            <span className="field-label">Clinical Model</span>
                                        </label>
                                        <label className="field checkbox">
                                            <input
                                                type="radio"
                                                name="text-extraction-role"
                                                checked={settings.parsingModel === model.name}
                                                onChange={() => { void handleRoleSelection("text_extraction", model.name); }}
                                                disabled={localSelectionDisabled}
                                            />
                                            <span className="field-label">Text Extraction</span>
                                        </label>
                                    </div>
                                </li>
                            ))}
                        </ul>
                    </div>

                    <div className={`model-config-ollama-row ${ollamaControlsDisabled ? "is-disabled" : ""}`} aria-disabled={ollamaControlsDisabled}>
                        <h2 className="modal-section-title">Ollama Settings</h2>
                        <label className="field checkbox">
                            <input
                                type="checkbox"
                                checked={settings.reasoning}
                                onChange={(e) => { void handleReasoningChange(e.target.checked); }}
                                disabled={ollamaControlsDisabled}
                            />
                            <span className="field-label">Enable SDL/Reasoning</span>
                        </label>
                    </div>
                </section>

                <section className="model-config-right-column">
                    <div className="model-config-cloud-row">
                        <h2 className="modal-section-title">Cloud Model Control</h2>
                        <label className="field checkbox">
                            <input
                                type="checkbox"
                                checked={cloudEnabled}
                                onChange={(e) => { void handleCloudSwitchChange(e.target.checked); }}
                                disabled={isSaving || isLoading}
                            />
                            <span className="field-label">Use Cloud Models</span>
                        </label>

                        <div className="model-config-provider-grid">
                            <div className="model-config-provider-list">
                                {providerOptions.map((provider) => (
                                    <div
                                        key={provider}
                                        className={`model-config-provider-card ${activeProvider === provider ? "is-active" : ""}`}
                                    >
                                        <button
                                            className="model-config-provider-button"
                                            type="button"
                                            onClick={() => { void handleProviderChange(provider); }}
                                            disabled={!cloudEnabled || isSaving || isLoading}
                                        >
                                            <span>{PROVIDER_LABELS[provider] || provider}</span>
                                        </button>
                                        <button
                                            className="model-config-provider-key"
                                            type="button"
                                            onClick={() => {
                                                if (isAccessKeyProvider(provider)) {
                                                    setOpenProviderModal(provider);
                                                }
                                            }}
                                            disabled={isSaving || isLoading}
                                            aria-label={`Manage ${PROVIDER_LABELS[provider] || provider} access keys`}
                                        >
                                            <KeyIcon />
                                        </button>
                                    </div>
                                ))}
                                <div className="model-config-provider-card">
                                    <button
                                        className="model-config-provider-button"
                                        type="button"
                                        onClick={() => setOpenProviderModal("tavily")}
                                        disabled={isSaving || isLoading}
                                    >
                                        <span>Research provider</span>
                                        <span className="model-config-provider-hint">Tavily API key</span>
                                    </button>
                                    <button
                                        className="model-config-provider-key"
                                        type="button"
                                        onClick={() => setOpenProviderModal("tavily")}
                                        disabled={isSaving || isLoading}
                                        aria-label="Manage Tavily access keys"
                                    >
                                        <KeyIcon />
                                    </button>
                                </div>
                            </div>

                            <div className="field">
                                <label className="field-label" htmlFor="cloud-model-select">Cloud Model</label>
                                <select
                                    id="cloud-model-select"
                                    value={activeCloudModel || ""}
                                    onChange={(e) => { void handleCloudModelChange(e.target.value); }}
                                    disabled={!cloudEnabled || isSaving || isLoading || !activeCloudModels.length}
                                >
                                    {activeCloudModels.map((modelName) => (
                                        <option key={modelName} value={modelName}>
                                            {modelName}
                                        </option>
                                    ))}
                                </select>
                            </div>
                        </div>
                    </div>

                    <div className="model-config-right-footer-row">
                        <h2 className="modal-section-title">Current Selection Summary</h2>
                        <table className="model-config-summary-table" aria-label="Current selection summary">
                            <tbody>
                                <tr>
                                    <th scope="row">Clinical</th>
                                    <td>{settings.clinicalModel || "Not set"}</td>
                                    <td className={clinicalAvailabilityClassName}>
                                        {clinicalAvailabilityLabel}
                                    </td>
                                </tr>
                                <tr>
                                    <th scope="row">Text Extraction</th>
                                    <td>{settings.parsingModel || "Not set"}</td>
                                    <td className={extractionAvailabilityClassName}>
                                        {extractionAvailabilityLabel}
                                    </td>
                                </tr>
                                <tr>
                                    <th scope="row">Provider</th>
                                    <td>{PROVIDER_LABELS[activeProvider] || activeProvider}</td>
                                    <td>{cloudEnabled ? "Cloud active" : "Cloud disabled"}</td>
                                </tr>
                                <tr>
                                    <th scope="row">Cloud Model</th>
                                    <td>{activeCloudModel || "Not set"}</td>
                                    <td>{cloudEnabled ? "In use" : "Standby"}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </section>
            </div>

            <StatusMessage message={statusMessage} tone={statusTone} />
            <AccessKeyModal
                isOpen={openProviderModal !== null}
                provider={openProviderModal ?? "openai"}
                providerLabel={PROVIDER_LABELS[openProviderModal ?? "openai"] || (openProviderModal ?? "openai")}
                onClose={() => setOpenProviderModal(null)}
            />
        </main>
    );
}
