// DILIGENT/client/src/components/ProviderAccessCard.tsx
import React from "react";

const KeyIcon = (): React.JSX.Element => (
  <svg
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <circle cx="8" cy="15" r="3" />
    <path d="M11 15h10" />
    <path d="M18 12v6" />
  </svg>
);

type SelectableProviderAccessCardProps = {
  readonly variant: "selectable";
  readonly label: string;
  readonly isActive: boolean;
  readonly disabled: boolean;
  readonly onSelect: () => void;
  readonly onManageKeys: () => void;
  readonly manageKeyAriaLabel: string;
};

type CompactProviderAccessCardProps = {
  readonly variant: "compact";
  readonly label: string;
  readonly hint: string;
  readonly disabled: boolean;
  readonly onManageKeys: () => void;
  readonly manageKeyAriaLabel: string;
};

type ProviderAccessCardProps =
  | SelectableProviderAccessCardProps
  | CompactProviderAccessCardProps;

export function ProviderAccessCard(
  props: ProviderAccessCardProps,
): React.JSX.Element {
  const isCompact = props.variant === "compact";
  const className = [
    "model-config-provider-card",
    !isCompact && props.isActive ? "is-active" : "",
    isCompact ? "model-config-provider-card-compact" : "",
  ]
    .filter(Boolean)
    .join(" ");

  return (
    <div className={className}>
      {isCompact ? (
        <button
          className="model-config-provider-button"
          type="button"
          onClick={props.onManageKeys}
          disabled={props.disabled}
        >
          <span>{props.label}</span>
          <span className="model-config-provider-hint">{props.hint}</span>
        </button>
      ) : (
        <button
          className="model-config-provider-button"
          type="button"
          onClick={props.onSelect}
          disabled={props.disabled}
        >
          <span>{props.label}</span>
        </button>
      )}
      <button
        className="model-config-provider-key"
        type="button"
        onClick={props.onManageKeys}
        disabled={props.disabled}
        aria-label={props.manageKeyAriaLabel}
      >
        <KeyIcon />
      </button>
    </div>
  );
}

// app/client/src/app/components/provider-access-card/provider-access-card.component.ts
import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'app-provider-access-card',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './provider-access-card.component.html',
})
export class ProviderAccessCardComponent {
  @Input() variant: 'selectable' | 'compact' = 'selectable';
  @Input() label = '';
  @Input() isActive = false;
  @Input() disabled = false;
  @Input() hint = '';
  @Input() manageKeyAriaLabel = 'Manage provider access keys';

  @Output() select = new EventEmitter<void>();
  @Output() manageKeys = new EventEmitter<void>();

  get isCompact(): boolean {
    return this.variant === 'compact';
  }

  get className(): string {
    return [
      'model-config-provider-card',
      !this.isCompact && this.isActive ? 'is-active' : '',
      this.isCompact ? 'model-config-provider-card-compact' : '',
    ]
      .filter(Boolean)
      .join(' ');
  }
}

<div [class]="className">
  @if (isCompact) {
    <button
      class="model-config-provider-button"
      type="button"
      (click)="manageKeys.emit()"
      [disabled]="disabled"
    >
      <span>{{ label }}</span>
      <span class="model-config-provider-hint">{{ hint }}</span>
    </button>
  } @else {
    <button
      class="model-config-provider-button"
      type="button"
      (click)="select.emit()"
      [disabled]="disabled"
    >
      <span>{{ label }}</span>
    </button>
  }
  <button
    class="model-config-provider-key"
    type="button"
    (click)="manageKeys.emit()"
    [disabled]="disabled"
    [attr.aria-label]="manageKeyAriaLabel"
  >
    <svg viewBox="0 0 24 24" aria-hidden="true">
      <path d="M7.75 13.75a3.5 3.5 0 1 1 3.12-5.08l.16.31h7.22a1 1 0 0 1 .7.3l1.8 1.82-2.12 2.12-1.25-1.25-1.45 1.45-1.23-1.23-3.67.01-.16.31a3.49 3.49 0 0 1-3.12 1.94Zm0-2.25a1.25 1.25 0 1 0 0-2.5 1.25 1.25 0 0 0 0 2.5Z" />
    </svg>
  </button>
</div>
