// DILIGENT/client/src/pages/DiliAgentPage.tsx
import React, { useCallback, useEffect, useRef, useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

import { BooleanToggle } from "../components/BooleanToggle";
import {
    DEFAULT_FORM_STATE,
    REPORT_EXPORT_FILENAME,
} from "../constants";
import { useAppState } from "../context/AppStateContext";
import { useObjectUrlLifecycle } from "../hooks/useObjectUrlLifecycle";
import {
    cancelClinicalJob,
    pollClinicalJobStatus,
    startClinicalJob,
} from "../services/api";
import { JobStatus, JobStatusResponse } from "../types";
import {
    buildClinicalPayload,
    createDownloadUrl,
    normalizeVisitDateInput,
} from "../utils";

const todayIso = new Date().toISOString().slice(0, 10);
const DEFAULT_POLL_INTERVAL_MS = 1000;

// ---------------------------------------------------------------------------
// Icons
// ---------------------------------------------------------------------------
const CopyIcon = () => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
        <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
    </svg>
);

const ExpandIcon = () => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <polyline points="15 3 21 3 21 9" />
        <polyline points="9 21 3 21 3 15" />
        <line x1="21" y1="3" x2="14" y2="10" />
        <line x1="3" y1="21" x2="10" y2="14" />
    </svg>
);

const DownloadIcon = () => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
        <polyline points="7 10 12 15 17 10" />
        <line x1="12" y1="15" x2="12" y2="3" />
    </svg>
);

const ClinicalInputIcon = ({ kind }: { kind: "anamnesis" | "drugs" | "labs" }) => {
    if (kind === "anamnesis") {
        return (
            <svg viewBox="0 0 24 24" aria-hidden="true">
                <path d="M6 4h9l3 3v13H6z" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
                <path d="M15 4v3h3" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
                <path d="M9 12h6M9 16h6" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" />
            </svg>
        );
    }
    if (kind === "drugs") {
        return (
            <svg viewBox="0 0 24 24" aria-hidden="true">
                <rect x="4" y="8" width="16" height="8" rx="4" fill="none" stroke="currentColor" strokeWidth="1.8" />
                <path d="M12 8v8" fill="none" stroke="currentColor" strokeWidth="1.8" />
            </svg>
        );
    }
    return (
        <svg viewBox="0 0 24 24" aria-hidden="true">
            <path d="M6 4h8l4 4v12H6z" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
            <path d="M14 4v4h4M9 13h6M9 17h4" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
        </svg>
    );
};

function isTerminalJobStatus(status: JobStatus | null): boolean {
    return status === "completed" || status === "failed" || status === "cancelled";
}

// ---------------------------------------------------------------------------
// DiliAgentPage
// ---------------------------------------------------------------------------
export function DiliAgentPage(): React.JSX.Element {
    const { state, updateDiliAgent } = useAppState();
    const {
        settings,
        form,
        message,
        exportUrl,
        jobId,
        jobProgress,
        jobStatus,
        jobStageMessage,
        isRunning,
        isExpanded,
    } = state.diliAgent;

    const pollerRef = useRef<{ stop: () => void } | null>(null);
    const [isCancelling, setIsCancelling] = useState(false);
    const { revokeObjectUrl } = useObjectUrlLifecycle(exportUrl);

    // Cleanup poller on unmount
    useEffect(() => {
        return () => {
            if (pollerRef.current) {
                pollerRef.current.stop();
                pollerRef.current = null;
            }
        };
    }, []);

    // ---------------------------------------------------------------------------
    // Handlers
    // ---------------------------------------------------------------------------
    const resetOutputs = () => {
        revokeObjectUrl(exportUrl);
        updateDiliAgent({
            message: "",
            exportUrl: null,
            jobId: null,
            jobProgress: 0,
            jobStatus: null,
            jobStage: null,
            jobStageMessage: null,
        });
    };

    const handleFormChange = <K extends keyof typeof form>(key: K, value: (typeof form)[K]) => {
        updateDiliAgent({ form: { ...form, [key]: value } });
    };

    const handleVisitDateChange = (value: string) => {
        handleFormChange("visitDate", normalizeVisitDateInput(value));
    };

    const stopPoller = useCallback(() => {
        if (pollerRef.current) {
            pollerRef.current.stop();
            pollerRef.current = null;
        }
    }, []);

    const handlePollingError = useCallback(
        (pollError: string) => {
            stopPoller();
            setIsCancelling(false);
            updateDiliAgent({
                message: `[ERROR] ${pollError}`,
                exportUrl: null,
                jobStage: null,
                jobStageMessage: null,
                isRunning: false,
            });
        },
        [stopPoller, updateDiliAgent],
    );

    const handleJobStatusUpdate = useCallback(
        (status: JobStatusResponse) => {
            const terminalStatus = isTerminalJobStatus(status.status);
            const stage =
                status.result && typeof status.result.progress_stage === "string"
                    ? status.result.progress_stage
                    : null;
            const stageMessage =
                status.result && typeof status.result.progress_message === "string"
                    ? status.result.progress_message
                    : null;
            const resolvedProgress =
                typeof status.progress === "number" ? status.progress : 0;
            updateDiliAgent({
                jobProgress: terminalStatus ? 100 : resolvedProgress,
                jobStatus: status.status,
                jobStage: stage,
                jobStageMessage: stageMessage,
                isRunning: !terminalStatus,
            });

            if (!terminalStatus) {
                return;
            }

            stopPoller();
            setIsCancelling(false);

            if (status.status === "completed") {
                const report =
                    typeof status.result?.report === "string"
                        ? status.result.report
                        : "";
                const newExportUrl = report
                    ? createDownloadUrl(report, REPORT_EXPORT_FILENAME)
                    : null;
                updateDiliAgent({
                    message: report || "[INFO] Clinical analysis completed.",
                    exportUrl: newExportUrl,
                    jobStage: null,
                    jobStageMessage: null,
                });
            } else if (status.status === "failed") {
                const errorMessage = status.error
                    ? `[ERROR] ${status.error}`
                    : "[ERROR] Clinical analysis failed.";
                updateDiliAgent({
                    message: errorMessage,
                    exportUrl: null,
                    jobStage: null,
                    jobStageMessage: null,
                });
            } else if (status.status === "cancelled") {
                updateDiliAgent({
                    message: "[INFO] Clinical analysis cancelled.",
                    exportUrl: null,
                    jobStage: null,
                    jobStageMessage: null,
                });
            }
        },
        [stopPoller, updateDiliAgent],
    );

    const startPolling = useCallback(
        (jobIdToPoll: string, intervalMs: number) => {
            stopPoller();
            pollerRef.current = pollClinicalJobStatus(
                jobIdToPoll,
                intervalMs,
                handleJobStatusUpdate,
                handlePollingError,
            );
        },
        [handleJobStatusUpdate, handlePollingError, stopPoller],
    );

    const executeRunSession = async () => {
        setIsCancelling(false);
        updateDiliAgent({ isRunning: true });
        resetOutputs();
        stopPoller();
        try {
            const payload = buildClinicalPayload(form, settings);
            const startResult = await startClinicalJob(payload);
            updateDiliAgent({
                jobId: startResult.job_id,
                jobProgress: 0,
                jobStatus: startResult.status,
                jobStage: "session_initialization",
                jobStageMessage: "Initializing clinical session",
            });
            const intervalMs = startResult.poll_interval * 1000;
            startPolling(startResult.job_id, intervalMs);
        } catch (error) {
            const description =
                error instanceof Error ? error.message : "Unexpected error";
            updateDiliAgent({
                message: `[ERROR] ${description}`,
                exportUrl: null,
                jobStage: null,
                jobStageMessage: null,
                isRunning: false,
            });
        } finally {
            if (!pollerRef.current) {
                updateDiliAgent({ isRunning: false });
            }
        }
    };

    useEffect(() => {
        if (!isRunning || !jobId || isTerminalJobStatus(jobStatus) || pollerRef.current) {
            return;
        }
        startPolling(jobId, DEFAULT_POLL_INTERVAL_MS);
    }, [isRunning, jobId, jobStatus, startPolling]);

    const handleRunSession = async () => {
        const missingMessageByField: Array<[keyof typeof form, string]> = [
            ["anamnesis", "[ERROR] Provide the anamnesis."],
            ["visitDate", "[ERROR] Provide the visit date."],
            ["drugs", "[ERROR] Provide current drugs."],
            [
                "laboratoryAnalysis",
                "[ERROR] Provide laboratory data sufficient to determine hepatotoxicity pattern, ideally dated ALT or AST, ALP, and bilirubin.",
            ],
        ];
        const firstMissing = missingMessageByField.find(
            ([field]) => !String(form[field]).trim(),
        );
        if (firstMissing) {
            resetOutputs();
            updateDiliAgent({
                isRunning: false,
                message: firstMissing[1],
                exportUrl: null,
                jobStage: null,
                jobStageMessage: null,
            });
            return;
        }
        await executeRunSession();
    };

    const handleStopSession = async () => {
        if (!jobId) {
            return;
        }
        setIsCancelling(true);
        try {
            await cancelClinicalJob(jobId);
            updateDiliAgent({
                message: "[INFO] Cancellation requested. Waiting for worker shutdown...",
            });
        } catch (error) {
            const description =
                error instanceof Error ? error.message : "Failed to request cancellation.";
            updateDiliAgent({
                message: `[ERROR] ${description}`,
            });
        } finally {
            setIsCancelling(false);
        }
    };

    const handleClear = () => {
        revokeObjectUrl(exportUrl);
        updateDiliAgent({
            form: { ...DEFAULT_FORM_STATE },
            message: "",
            exportUrl: null,
            jobId: null,
            jobProgress: 0,
            jobStatus: null,
            jobStage: null,
            jobStageMessage: null,
        });
    };

    const handleDownload = () => {
        if (!exportUrl) return;
        const anchor = document.createElement("a");
        anchor.href = exportUrl;
        anchor.download = REPORT_EXPORT_FILENAME;
        anchor.click();
    };

    const handleCopyReport = async () => {
        if (message) {
            try {
                await navigator.clipboard.writeText(message);
            } catch (err) {
                console.error("Failed to copy:", err);
            }
        }
    };

    const handleToggleExpand = () => {
        updateDiliAgent({ isExpanded: !isExpanded });
    };

    const recordedDateLabel = form.visitDate
        ? new Date(`${form.visitDate}T00:00:00`).toLocaleDateString(undefined, {
            year: "numeric",
            month: "long",
            day: "numeric",
        })
        : "Not set";
    const patientNameLabel = form.patientName.trim() || "Unnamed patient";

    // ---------------------------------------------------------------------------
    // Render
    // ---------------------------------------------------------------------------
    const spinner = (
        <div className="session-spinner" role="status" aria-live="polite">
            <div className="spinner-wheel" />
            <p className="spinner-label">
                {`${jobStageMessage || "Generating report"}${
                    jobProgress > 0 ? `... ${Math.round(jobProgress)}%` : "..."
                }`}
            </p>
        </div>
    );

    const reportContent = (() => {
        if (isRunning && !isTerminalJobStatus(jobStatus)) {
            return spinner;
        }
        if (message) {
            return (
                <ReactMarkdown remarkPlugins={[remarkGfm]} className="markdown">
                    {message}
                </ReactMarkdown>
            );
        }
        return (
            <div className="report-placeholder">
                No report generated yet. Run analysis to see results.
            </div>
        );
    })();
    return (
        <main className="page-container stitch-dili-page">
            <div className="stitch-dili-grid">
                <div className="stitch-dili-main">
                    <section className="stitch-dili-card">
                        <div className="stitch-dili-input-stack">
                            <div className="stitch-dili-input-group">
                                <h3><ClinicalInputIcon kind="anamnesis" /><span>Anamnesis</span></h3>
                                <textarea
                                    id="anamnesis"
                                    placeholder="Describe patient history, symptoms onset, and clinical observations..."
                                    value={form.anamnesis}
                                    onChange={(e) => handleFormChange("anamnesis", e.target.value)}
                                />
                            </div>

                            <div className="stitch-dili-input-group">
                                <h3><ClinicalInputIcon kind="drugs" /><span>Current Drugs</span></h3>
                                <textarea
                                    id="drugs"
                                    placeholder="List medications, dosages, frequency, and duration of use..."
                                    value={form.drugs}
                                    onChange={(e) => handleFormChange("drugs", e.target.value)}
                                />
                            </div>

                            <div className="stitch-dili-input-group">
                                <h3><ClinicalInputIcon kind="labs" /><span>Laboratory Analysis</span></h3>
                                <textarea
                                    id="laboratory-analysis"
                                    placeholder="Input raw lab results (ALT, AST, ALP, Bilirubin, etc.)..."
                                    value={form.laboratoryAnalysis}
                                    onChange={(e) => handleFormChange("laboratoryAnalysis", e.target.value)}
                                />
                            </div>
                        </div>
                    </section>
                </div>

                <aside className="stitch-dili-sidebar">
                    <section className="stitch-dili-card stitch-dili-patient">
                        <div className="stitch-dili-patient-top">
                            <div className="stitch-dili-avatar" aria-hidden="true">
                                {patientNameLabel.charAt(0).toUpperCase()}
                            </div>
                            <div>
                                <h3>{patientNameLabel}</h3>
                                <p>Recorded: {recordedDateLabel}</p>
                            </div>
                        </div>

                        <div className="stitch-dili-inline-fields">
                            <div className="field">
                                <label className="field-label" htmlFor="patient-name">Patient Name</label>
                                <input
                                    id="patient-name"
                                    type="text"
                                    placeholder="e.g., Marco Rossi"
                                    value={form.patientName}
                                    onChange={(e) => handleFormChange("patientName", e.target.value)}
                                />
                            </div>
                            <div className="field">
                                <label className="field-label" htmlFor="visit-date">Visit Date</label>
                                <input
                                    id="visit-date"
                                    type="date"
                                    max={todayIso}
                                    value={form.visitDate}
                                    onChange={(e) => handleVisitDateChange(e.target.value)}
                                />
                            </div>
                        </div>

                        <div className="stitch-dili-controls">
                            <p>Retrieval Controls</p>
                            <BooleanToggle
                                id="use-rag"
                                label="Internal RAG"
                                checked={form.useRag}
                                onChange={(checked) => handleFormChange("useRag", checked)}
                            />
                            <BooleanToggle
                                id="use-web-search"
                                label="Web Search"
                                checked={form.useWebSearch}
                                onChange={(checked) => handleFormChange("useWebSearch", checked)}
                            />
                        </div>

                        <div className="stitch-dili-actions">
                            <button
                                className="btn btn-primary"
                                type="button"
                                disabled={isCancelling}
                                onClick={() => { void (isRunning ? handleStopSession() : handleRunSession()); }}
                            >
                                {isRunning ? (isCancelling ? "Stopping..." : "Stop analysis") : "Run DILI analysis"}
                            </button>
                            <button className="stitch-dili-clear" type="button" onClick={handleClear} disabled={isRunning}>
                                Clear all
                            </button>
                        </div>
                    </section>

                    <div className="stitch-dili-tip">
                        "Ensure laboratory results include units for accurate drug-induced liver injury risk profiling."
                    </div>
                </aside>
            </div>

            <section className="report-section stitch-dili-report">
                <div className="report-shell">
                    <div className="report-header">
                        <p className="report-eyebrow">Report Output</p>
                    </div>

                    <div className="report-toolbar">
                        <button
                            className="toolbar-btn"
                            type="button"
                            onClick={handleCopyReport}
                            disabled={!message}
                            title="Copy to clipboard"
                        >
                            <CopyIcon />
                            <span>Copy</span>
                        </button>
                        <button
                            className="toolbar-btn"
                            type="button"
                            onClick={handleToggleExpand}
                            disabled={!message}
                            title={isExpanded ? "Collapse" : "Expand"}
                        >
                            <ExpandIcon />
                            <span>{isExpanded ? "Collapse" : "Expand"}</span>
                        </button>
                        <button
                            className="toolbar-btn"
                            type="button"
                            onClick={handleDownload}
                            disabled={!exportUrl}
                            title="Download markdown file"
                        >
                            <DownloadIcon />
                            <span>Download markdown</span>
                        </button>
                    </div>

                    <div className={`report-content ${isExpanded ? "is-expanded" : ""}`}>
                        {reportContent}
                    </div>
                </div>
            </section>
        </main>
    );
}

// DILIGENT/client/src/app/pages/dili-agent/dili-agent-page.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnDestroy, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';

import { ModalShellComponent } from '../../components/modal-shell/modal-shell.component';
import { DEFAULT_FORM_STATE, REPORT_EXPORT_FILENAME } from '../../core/constants';
import { AppStateService } from '../../core/state/app-state.service';
import {
  buildClinicalPayload,
  createDownloadUrl,
  formatErrorMessage,
  formatUnknownError,
  normalizeVisitDateInput,
} from '../../core/utils';
import {
  JobStatus,
  JobStatusResponse,
} from '../../core/models/types';
import {
  cancelClinicalJob,
  pollClinicalJobStatus,
  startClinicalJob,
} from '../../core/services/api';

const todayIso = new Date().toISOString().slice(0, 10);
const DEFAULT_POLL_INTERVAL_MS = 1000;

function isTerminalJobStatus(status: JobStatus | null): boolean {
  return status === 'completed' || status === 'failed' || status === 'cancelled';
}

@Component({
  selector: 'app-dili-agent-page',
  imports: [CommonModule, FormsModule, ModalShellComponent],
  templateUrl: './dili-agent-page.component.html',
  styleUrl: './dili-agent-page.component.scss',
})
export class DiliAgentPageComponent implements OnDestroy {
  readonly stateService = inject(AppStateService);

  readonly isCancelling = signal(false);
  readonly isMissingLabsModalOpen = signal(false);
  readonly todayIso = todayIso;

  private poller: { stop: () => void } | null = null;

  get vm() {
    return this.stateService.state().diliAgent;
  }

  ngOnDestroy(): void {
    this.stopPoller();
    this.revokeObjectUrl();
  }

  handleFormChange<K extends keyof typeof this.vm.form>(key: K, value: (typeof this.vm.form)[K]): void {
    this.stateService.updateDiliAgent({
      form: {
        ...this.vm.form,
        [key]: value,
      },
    });
  }

  handleVisitDateChange(value: string): void {
    this.handleFormChange('visitDate', normalizeVisitDateInput(value));
  }

  private revokeObjectUrl(): void {
    if (this.vm.exportUrl) {
      URL.revokeObjectURL(this.vm.exportUrl);
    }
  }

  private resetOutputs(): void {
    this.revokeObjectUrl();
    this.stateService.updateDiliAgent({
      message: '',
      exportUrl: null,
      jobId: null,
      jobProgress: 0,
      jobStatus: null,
      jobStage: null,
      jobStageMessage: null,
    });
  }

  private stopPoller(): void {
    if (this.poller) {
      this.poller.stop();
      this.poller = null;
    }
  }

  private onPollingError(pollError: string): void {
    this.stopPoller();
    this.isCancelling.set(false);
    this.stateService.updateDiliAgent({
      message: formatErrorMessage(pollError),
      exportUrl: null,
      jobStage: null,
      jobStageMessage: null,
      isRunning: false,
    });
  }

  private onJobStatusUpdate(status: JobStatusResponse): void {
    const terminalStatus = isTerminalJobStatus(status.status);
    const stage =
      status.result && typeof status.result.progress_stage === 'string'
        ? status.result.progress_stage
        : null;
    const stageMessage =
      status.result && typeof status.result.progress_message === 'string'
        ? status.result.progress_message
        : null;
    const resolvedProgress = typeof status.progress === 'number' ? status.progress : 0;

    this.stateService.updateDiliAgent({
      jobProgress: terminalStatus ? 100 : resolvedProgress,
      jobStatus: status.status,
      jobStage: stage,
      jobStageMessage: stageMessage,
      isRunning: !terminalStatus,
    });

    if (!terminalStatus) {
      return;
    }

    this.stopPoller();
    this.isCancelling.set(false);

    if (status.status === 'completed') {
      const report = typeof status.result?.report === 'string' ? status.result.report : '';
      const newExportUrl = report ? createDownloadUrl(report, REPORT_EXPORT_FILENAME) : null;
      this.stateService.updateDiliAgent({
        message: report || '[INFO] Clinical analysis completed.',
        exportUrl: newExportUrl,
        jobStage: null,
        jobStageMessage: null,
      });
    } else if (status.status === 'failed') {
      const errorMessage = status.error
        ? formatErrorMessage(status.error)
        : '[ERROR] Clinical analysis failed.';
      this.stateService.updateDiliAgent({
        message: errorMessage,
        exportUrl: null,
        jobStage: null,
        jobStageMessage: null,
      });
    } else if (status.status === 'cancelled') {
      this.stateService.updateDiliAgent({
        message: '[INFO] Clinical analysis cancelled.',
        exportUrl: null,
        jobStage: null,
        jobStageMessage: null,
      });
    }
  }

  private startPolling(jobIdToPoll: string, intervalMs: number): void {
    this.stopPoller();
    this.poller = pollClinicalJobStatus(
      jobIdToPoll,
      intervalMs,
      (status) => this.onJobStatusUpdate(status),
      (message) => this.onPollingError(message),
    );
  }

  private async executeRunSession(allowMissingLabs: boolean | null): Promise<void> {
    this.isCancelling.set(false);
    this.stateService.updateDiliAgent({ isRunning: true });
    this.resetOutputs();
    this.stopPoller();

    try {
      const payload = buildClinicalPayload(this.vm.form, this.vm.settings, allowMissingLabs);
      const startResult = await startClinicalJob(payload);
      this.stateService.updateDiliAgent({
        jobId: startResult.job_id,
        jobProgress: 0,
        jobStatus: startResult.status,
        jobStage: 'session_initialization',
        jobStageMessage: 'Initializing clinical session',
      });
      const intervalMs = startResult.poll_interval * 1000;
      this.startPolling(startResult.job_id, intervalMs);
    } catch (error) {
      this.stateService.updateDiliAgent({
        message: formatUnknownError(error, 'Unexpected error'),
        exportUrl: null,
        jobStage: null,
        jobStageMessage: null,
        isRunning: false,
      });
    }
  }

  async runSession(): Promise<void> {
    const form = this.vm.form;
    const missingMessageByField: Array<[keyof typeof form, string]> = [
      ['anamnesis', '[ERROR] Provide the anamnesis.'],
      ['visitDate', '[ERROR] Provide the visit date.'],
      ['drugs', '[ERROR] Provide current drugs.'],
    ];

    const firstMissing = missingMessageByField.find(([field]) => !String(form[field]).trim());
    if (firstMissing) {
      this.resetOutputs();
      this.stateService.updateDiliAgent({
        isRunning: false,
        message: firstMissing[1],
      });
      return;
    }

    if (!form.laboratoryAnalysis.trim()) {
      this.resetOutputs();
      this.isMissingLabsModalOpen.set(true);
      return;
    }

    await this.executeRunSession(null);
  }

  cancelMissingLabs(): void {
    this.isMissingLabsModalOpen.set(false);
  }

  async confirmMissingLabs(): Promise<void> {
    this.isMissingLabsModalOpen.set(false);
    await this.executeRunSession(true);
  }

  async stopSession(): Promise<void> {
    if (!this.vm.jobId) {
      return;
    }
    this.isCancelling.set(true);
    try {
      await cancelClinicalJob(this.vm.jobId);
      this.stateService.updateDiliAgent({
        message: '[INFO] Cancellation requested. Waiting for worker shutdown...',
      });
    } catch (error) {
      this.stateService.updateDiliAgent({
        message: formatUnknownError(error, 'Failed to request cancellation.'),
      });
    } finally {
      this.isCancelling.set(false);
    }
  }

  clearAll(): void {
    this.revokeObjectUrl();
    this.stateService.updateDiliAgent({
      form: { ...DEFAULT_FORM_STATE },
      message: '',
      exportUrl: null,
      jobId: null,
      jobProgress: 0,
      jobStatus: null,
      jobStage: null,
      jobStageMessage: null,
    });
  }

  copyReport(): void {
    const message = this.vm.message;
    if (!message) return;
    void navigator.clipboard.writeText(message);
  }

  toggleExpand(): void {
    this.stateService.updateDiliAgent({ isExpanded: !this.vm.isExpanded });
  }

  downloadReport(): void {
    if (!this.vm.exportUrl) return;
    const anchor = document.createElement('a');
    anchor.href = this.vm.exportUrl;
    anchor.download = REPORT_EXPORT_FILENAME;
    anchor.click();
  }

  runOrStop(): void {
    if (this.vm.isRunning) {
      void this.stopSession();
      return;
    }
    void this.runSession();
  }

  get showSpinner(): boolean {
    return this.vm.isRunning && !isTerminalJobStatus(this.vm.jobStatus);
  }

  get reportBody(): string {
    return this.vm.message || 'No report generated yet. Run analysis to see results.';
  }

  get patientNameLabel(): string {
    return this.vm.form.patientName.trim() || 'Unnamed patient';
  }

  get recordedDateLabel(): string {
    if (!this.vm.form.visitDate) {
      return 'Not set';
    }
    return new Date(`${this.vm.form.visitDate}T00:00:00`).toLocaleDateString(undefined, {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
  }

  get defaultPollIntervalMs(): number {
    return DEFAULT_POLL_INTERVAL_MS;
  }
}

<main class="page-container stitch-dili-page">
  <header class="stitch-dili-heading">
    <h1>Drug-Induced Liver Injury analysis</h1>
    <p>Clinical Copilot</p>
  </header>

  <div class="stitch-dili-grid">
    <div class="stitch-dili-main">
      <section class="stitch-dili-card">
        <div class="stitch-dili-input-stack">
          <div class="stitch-dili-input-group">
            <h3>Anamnesis</h3>
            <textarea
              id="anamnesis"
              aria-label="Anamnesis"
              placeholder="Describe patient history, symptoms onset, and clinical observations..."
              [ngModel]="vm.form.anamnesis"
              (ngModelChange)="handleFormChange('anamnesis', $event)"
            ></textarea>
          </div>

          <div class="stitch-dili-input-group">
            <h3>Current Drugs</h3>
            <textarea
              id="drugs"
              aria-label="Current Drugs"
              placeholder="List medications, dosages, frequency, and duration of use..."
              [ngModel]="vm.form.drugs"
              (ngModelChange)="handleFormChange('drugs', $event)"
            ></textarea>
          </div>

          <div class="stitch-dili-input-group">
            <h3>Laboratory Analysis</h3>
            <textarea
              id="laboratory-analysis"
              aria-label="Laboratory Analysis"
              placeholder="Input raw lab results (ALT, AST, ALP, Bilirubin, etc.)..."
              [ngModel]="vm.form.laboratoryAnalysis"
              (ngModelChange)="handleFormChange('laboratoryAnalysis', $event)"
            ></textarea>
          </div>
        </div>
      </section>
    </div>

    <aside class="stitch-dili-sidebar">
      <section class="stitch-dili-card stitch-dili-patient">
        <div class="stitch-dili-patient-top">
          <div class="stitch-dili-avatar" aria-hidden="true">
            {{ patientNameLabel.charAt(0).toUpperCase() }}
          </div>
          <div>
            <h3>{{ patientNameLabel }}</h3>
            <p>Recorded: {{ recordedDateLabel }}</p>
          </div>
        </div>

        <div class="stitch-dili-inline-fields">
          <div class="field">
            <label class="field-label" for="patient-name">Patient Name</label>
            <input
              id="patient-name"
              type="text"
              placeholder="e.g., Marco Rossi"
              [ngModel]="vm.form.patientName"
              (ngModelChange)="handleFormChange('patientName', $event)"
            />
          </div>
          <div class="field">
            <label class="field-label" for="visit-date">Visit Date</label>
            <input
              id="visit-date"
              type="date"
              [max]="todayIso"
              [ngModel]="vm.form.visitDate"
              (ngModelChange)="handleVisitDateChange($event)"
            />
          </div>
        </div>

        <div class="stitch-dili-controls">
          <p>Retrieval Controls</p>
          <label class="toggle-row">
            <input
              type="checkbox"
              [ngModel]="vm.form.useRag"
              (ngModelChange)="handleFormChange('useRag', $event)"
            />
            <span class="toggle-label">Internal RAG</span>
          </label>
          <label class="toggle-row">
            <input
              type="checkbox"
              [ngModel]="vm.form.useWebSearch"
              (ngModelChange)="handleFormChange('useWebSearch', $event)"
            />
            <span class="toggle-label">Web Search</span>
          </label>
        </div>

        <div class="stitch-dili-actions">
          <button class="btn btn-primary" type="button" [disabled]="isCancelling()" (click)="runOrStop()">
            @if (vm.isRunning) {
              {{ isCancelling() ? 'Stopping...' : 'Stop analysis' }}
            } @else {
              Run DILI analysis
            }
          </button>
          <button class="stitch-dili-clear" type="button" (click)="clearAll()" [disabled]="vm.isRunning">
            Clear all
          </button>
        </div>
      </section>

    </aside>
  </div>

  <section class="report-section stitch-dili-report">
    <div class="report-shell">
      <div class="report-header">
        <p class="report-eyebrow">Report Output</p>
      </div>

      <div class="report-toolbar">
        <button class="toolbar-btn" type="button" (click)="copyReport()" [disabled]="!vm.message">
          Copy
        </button>
        <button class="toolbar-btn" type="button" (click)="toggleExpand()" [disabled]="!vm.message">
          {{ vm.isExpanded ? 'Collapse' : 'Expand' }}
        </button>
        <button class="toolbar-btn" type="button" (click)="downloadReport()" [disabled]="!vm.exportUrl">
          Download markdown
        </button>
      </div>

      <div class="report-content" [class.is-expanded]="vm.isExpanded">
        @if (showSpinner) {
          <div class="session-spinner" role="status" aria-live="polite">
            <div class="spinner-wheel"></div>
            <p class="spinner-label">
              {{ (vm.jobStageMessage || 'Generating report') + (vm.jobProgress > 0 ? ('... ' + (vm.jobProgress | number:'1.0-0') + '%') : '...') }}
            </p>
          </div>
        } @else {
          <pre class="inspection-excerpt-text">{{ reportBody }}</pre>
        }
      </div>
    </div>
  </section>
</main>

<app-modal-shell
  [isOpen]="isMissingLabsModalOpen()"
  title="Missing laboratory analysis"
  subtitle="Laboratory results are empty; hepatotoxicity pattern may be undetermined."
  titleId="missing-labs-title"
  ariaDescribedBy="missing-labs-description"
  [footer]="true"
  (close)="cancelMissingLabs()"
>
  <p id="missing-labs-description" class="helper">
    Continue only when you need to start an exploratory analysis before ALT, AST, ALP, and bilirubin
    values are available.
  </p>
  <div modal-footer>
    <button class="btn btn-secondary" type="button" (click)="cancelMissingLabs()">Cancel</button>
    <button class="btn btn-primary" type="button" (click)="confirmMissingLabs()">Continue anyway</button>
  </div>
</app-modal-shell>
